if(NOT DEFINED TEST_EXE)
  message(FATAL_ERROR "TEST_EXE is required")
endif()
if(NOT DEFINED TEST_OUTPUT)
  message(FATAL_ERROR "TEST_OUTPUT is required")
endif()
if(NOT DEFINED TEST_PYTHON)
  message(FATAL_ERROR "TEST_PYTHON is required")
endif()
if(NOT DEFINED TEST_GRAPHIMPL4_DOWNSIZED64_BIT_POSITIONS)
  message(FATAL_ERROR "TEST_GRAPHIMPL4_DOWNSIZED64_BIT_POSITIONS is required")
endif()
if(NOT DEFINED TEST_CARGO)
  set(TEST_CARGO "")
endif()
get_filename_component(test_output_parent "${TEST_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${test_output_parent}")

set(graphimpl4_keys "${test_output_parent}/graphimpl4_downsized64.keys")
set(generator_script "${test_output_parent}/generate_graphimpl4_downsized64_keys.py")
string(REPLACE "," ", " bit_positions_python
       "${TEST_GRAPHIMPL4_DOWNSIZED64_BIT_POSITIONS}")

file(WRITE "${generator_script}" "import struct\n")
file(APPEND "${generator_script}" "from pathlib import Path\n")
file(APPEND "${generator_script}" "path = Path(r'''${graphimpl4_keys}''')\n")
file(APPEND "${generator_script}" "positions = [${bit_positions_python}]\n")
file(APPEND "${generator_script}" "bitmap = sum(1 << position for position in positions)\n")
file(APPEND "${generator_script}" "def expand(value):\n")
file(APPEND "${generator_script}" "    result = 0\n")
file(APPEND "${generator_script}" "    for index, position in enumerate(positions):\n")
file(APPEND "${generator_script}" "        if value & (1 << index):\n")
file(APPEND "${generator_script}" "            result |= 1 << position\n")
file(APPEND "${generator_script}" "    return result\n")
file(APPEND "${generator_script}" "print(hex(bitmap))\n")
file(APPEND "${generator_script}" "with path.open('wb') as f:\n")
file(APPEND "${generator_script}" "    for value in range(1, 257):\n")
file(APPEND "${generator_script}" "        f.write(struct.pack('<Q', expand(value)))\n")

execute_process(
  COMMAND "${TEST_PYTHON}" "${generator_script}"
  RESULT_VARIABLE generate_result
  OUTPUT_VARIABLE generate_stdout
  ERROR_VARIABLE generate_stderr
)

if(NOT generate_result EQUAL 0)
  message(STATUS "stdout: ${generate_stdout}")
  message(STATUS "stderr: ${generate_stderr}")
  message(FATAL_ERROR "Failed to generate downsized GraphImpl4 key file")
endif()
string(STRIP "${generate_stdout}" downsize_bitmap)
if(downsize_bitmap STREQUAL "")
  message(FATAL_ERROR "Generator did not report the sparse 64-bit downsize bitmap")
endif()

set(TEST_KEYS "${graphimpl4_keys}")
set(TEST_ARGS "Chm01|MultiplyShiftR|And|1")
# Keep this seed triple in sync with kGraphImpl4Downsized64ReloadSeedsArg in
# PerfectHashOnlineTests.cpp; both cover the same downsized-64 key shape.
string(CONCAT TEST_FLAGS
  "--Quiet|--GraphImpl=4|--DoNotHashAllKeysFirst|--MaxSolveTimeInSeconds=5"
  "|--KeySizeInBytes=8|--Seeds=0xDDE48099,0x20C4AF8D,0x608")
set(TEST_SKIP_CREATE_RESULTS "129|136")

include("${CMAKE_CURRENT_LIST_DIR}/run_cli_codegen_test.cmake")
if(TEST_CODEGEN_SKIPPED)
  return()
endif()

require_file("${gen_dir}/${table_name}_DownsizedKeys.c")
if(CMAKE_HOST_WIN32)
  require_file("${gen_dir}/${table_name}.pht1:Info")
endif()

file(READ "${gen_dir}/${table_name}.h" generated_header)
string(FIND "${generated_header}" "extern const USHORT ${table_name}_TableData[]" has_ushort_table)
string(FIND "${generated_header}" "extern const ULONG ${table_name}_TableData[]" has_ulong_table)
if(NOT has_ushort_table LESS 0)
  set(expected_rust_table_type "u16")
  set(expected_cuda_table_type "std::uint16_t")
elseif(NOT has_ulong_table LESS 0)
  set(expected_rust_table_type "u32")
  set(expected_cuda_table_type "std::uint32_t")
else()
  message(FATAL_ERROR "Expected USHORT or ULONG table data declaration in generated header")
endif()
string(TOUPPER "${generated_header}" generated_header_upper)
string(TOUPPER "${downsize_bitmap}" downsize_bitmap_upper)
string(FIND "${generated_header_upper}" "${downsize_bitmap_upper}" has_header_downsize_bitmap)
if(has_header_downsize_bitmap LESS 0)
  message(FATAL_ERROR "Expected sparse 64-bit downsize bitmap in generated header")
endif()

file(READ "${gen_dir}/${table_name}_RustLib.rs" generated_rust)
string(FIND "${generated_rust}" "pub type TableDataType = ${expected_rust_table_type};" has_rust_table_type)
if(has_rust_table_type LESS 0)
  message(FATAL_ERROR "Expected ${expected_rust_table_type} table data type in generated Rust file")
endif()
string(FIND "${generated_rust}" "pub type OriginalKeyType = u64;" has_rust_u64)
if(has_rust_u64 LESS 0)
  message(FATAL_ERROR "Expected u64 original key type in generated Rust file")
endif()

file(READ "${gen_dir}/${table_name}.cu" generated_cuda)
string(FIND "${generated_cuda}" "using table_data_type = ${expected_cuda_table_type};" has_cuda_table_type)
if(has_cuda_table_type LESS 0)
  message(FATAL_ERROR "Expected ${expected_cuda_table_type} table data type in generated CUDA file")
endif()
string(FIND "${generated_cuda}" "using original_key_type = std::uint64_t;" has_cuda_u64)
if(has_cuda_u64 LESS 0)
  message(FATAL_ERROR "Expected uint64_t original key type in generated CUDA file")
endif()
