/*++

Copyright (c) 2025 Trent Nelson <trent@trent.me>

Module Name:

    Chm01FileWorkCppHeaderOnlyTestFile.c

Abstract:

    This module implements the save file work callback routine for the C++23
    header-only test file as part of the CHM v1 algorithm implementation for
    the perfect hash library.

--*/

#include "stdafx.h"

_Use_decl_annotations_
HRESULT
SaveCppHeaderOnlyTestFileChm01(
    PPERFECT_HASH_CONTEXT Context,
    PFILE_WORK_ITEM Item
    )
{
    PCHAR Base;
    PCHAR Output;
    PCSTRING Name;
    PPERFECT_HASH_FILE File;

    //
    // Initialize aliases.
    //

    UNREFERENCED_PARAMETER(Context);

    File = *Item->FilePointer;
    Name = &GetActivePath(File)->TableNameA;

    Base = (PCHAR)File->BaseAddress;
    Output = Base;

    //
    // Write test file.
    //

    OUTPUT_RAW("// Auto-generated by Perfect Hash.\n");
    OUTPUT_RAW("#include \"");
    OUTPUT_STRING(Name);
    OUTPUT_RAW("_CppHeaderOnly.hpp\"\n");
    OUTPUT_RAW("#include <cstdint>\n");
    OUTPUT_RAW("#include <iostream>\n");
    OUTPUT_RAW("#include <vector>\n\n");

    OUTPUT_RAW("int main() {\n");
    OUTPUT_RAW("    using namespace perfecthash::generated::");
    OUTPUT_STRING(Name);
    OUTPUT_RAW(";\n");
    OUTPUT_RAW("    if constexpr (!kSupported) {\n");
    OUTPUT_RAW("        std::cout << \"unsupported\" << std::endl;\n");
    OUTPUT_RAW("        return 0;\n");
    OUTPUT_RAW("    }\n");
    OUTPUT_RAW("    std::vector<std::uint8_t> seen(\n");
    OUTPUT_RAW("        static_cast<std::size_t>(index_mask) + 1, 0);\n");
    OUTPUT_RAW("    std::size_t count = 0;\n");
    OUTPUT_RAW("    for (auto key : keys) {\n");
    OUTPUT_RAW("        const auto idx = index(key);\n");
    OUTPUT_RAW("        const auto pos = static_cast<std::size_t>(idx);\n");
    OUTPUT_RAW("        if (pos >= seen.size()) {\n");
    OUTPUT_RAW("            return 1;\n");
    OUTPUT_RAW("        }\n");
    OUTPUT_RAW("        if (seen[pos]) {\n");
    OUTPUT_RAW("            return 1;\n");
    OUTPUT_RAW("        }\n");
    OUTPUT_RAW("        seen[pos] = 1;\n");
    OUTPUT_RAW("        ++count;\n");
    OUTPUT_RAW("    }\n");
    OUTPUT_RAW("    if (count != number_of_keys) {\n");
    OUTPUT_RAW("        return 1;\n");
    OUTPUT_RAW("    }\n");
    OUTPUT_RAW("    std::cout << \"ok\" << std::endl;\n");
    OUTPUT_RAW("    return 0;\n");
    OUTPUT_RAW("}\n");

    //
    // Update the number of bytes written.
    //

    File->NumberOfBytesWritten.QuadPart = RtlPointerToOffset(Base, Output);

    return S_OK;
}

// vim:set ts=8 sw=4 sts=4 tw=80 expandtab                                     :
