/*++

Copyright (c) 2025 Trent Nelson <trent@trent.me>

Module Name:

    Chm01FileWorkPythonTestFile.c

Abstract:

    This module implements the save file work callback routine for the Python
    test file as part of the CHM v1 algorithm implementation for the perfect
    hash library.

--*/

#include "stdafx.h"

_Use_decl_annotations_
HRESULT
SavePythonTestFileChm01(
    PPERFECT_HASH_CONTEXT Context,
    PFILE_WORK_ITEM Item
    )
{
    PCHAR Base;
    PCHAR Output;
    PCSTRING ModuleBaseName;
    PPERFECT_HASH_FILE File;
    PPERFECT_HASH_TABLE Table;

    //
    // Initialize aliases.
    //

    Table = Context->Table;
    File = *Item->FilePointer;
    ModuleBaseName = &Table->OutputDirectory->Path->BaseNameA;

    Base = (PCHAR)File->BaseAddress;
    Output = Base;

    //
    // Write test file.
    //

    OUTPUT_RAW("# Auto-generated by Perfect Hash.\n");
    OUTPUT_RAW("import importlib.util\n");
    OUTPUT_RAW("import os\n\n");

    OUTPUT_RAW("MODULE_FILENAME = \"");
    OUTPUT_STRING(ModuleBaseName);
    OUTPUT_RAW("_Python.py\"\n");
    OUTPUT_RAW("MODULE_PATH = os.path.join(os.path.dirname(__file__), ");
    OUTPUT_RAW("MODULE_FILENAME)\n");
    OUTPUT_RAW("spec = importlib.util.spec_from_file_location(\n");
    OUTPUT_RAW("    \"perfecthash_module\", MODULE_PATH)\n");
    OUTPUT_RAW("ph = importlib.util.module_from_spec(spec)\n");
    OUTPUT_RAW("spec.loader.exec_module(ph)\n\n");

    OUTPUT_RAW("def _assert_unique_indexes():\n");
    OUTPUT_RAW("    seen = {}\n");
    OUTPUT_RAW("    for key in ph.KEYS:\n");
    OUTPUT_RAW("        idx = ph.index(key)\n");
    OUTPUT_RAW("        if idx in seen:\n");
    OUTPUT_RAW("            raise AssertionError(\n");
    OUTPUT_RAW("                f\"collision: {key} -> {idx} ");
    OUTPUT_RAW("(prev {seen[idx]})\")\n");
    OUTPUT_RAW("        if idx < 0 or idx > ph.INDEX_MASK:\n");
    OUTPUT_RAW("            raise AssertionError(\n");
    OUTPUT_RAW("                f\"index out of range: {idx}\")\n");
    OUTPUT_RAW("        seen[idx] = key\n");
    OUTPUT_RAW("    if len(seen) != len(ph.KEYS):\n");
    OUTPUT_RAW("        raise AssertionError(\"index count mismatch\")\n\n");

    OUTPUT_RAW("if __name__ == \"__main__\":\n");
    OUTPUT_RAW("    if hasattr(ph, \"SUPPORTED\") and not ph.SUPPORTED:\n");
    OUTPUT_RAW("        print(\"unsupported\")\n");
    OUTPUT_RAW("    else:\n");
    OUTPUT_RAW("        _assert_unique_indexes()\n");
    OUTPUT_RAW("        print(\"ok\")\n");

    //
    // Update the number of bytes written.
    //

    File->NumberOfBytesWritten.QuadPart = RtlPointerToOffset(Base, Output);

    return S_OK;
}

// vim:set ts=8 sw=4 sts=4 tw=80 expandtab                                     :
