/*++

Copyright (c) 2026 Trent Nelson <trent@trent.me>

Module Name:

    Chm01FileWorkRustCargoTomlFile.c

Abstract:

    This module implements the save file work callback routine for the Rust
    Cargo.toml file as part of the CHM v1 algorithm implementation for the
    perfect hash library.

--*/

#include "stdafx.h"

_Use_decl_annotations_
HRESULT
SaveRustCargoTomlFileChm01(
    PPERFECT_HASH_CONTEXT Context,
    PFILE_WORK_ITEM Item
    )
{
    PCHAR Base;
    PCHAR Output;
    PCSTRING ModuleBaseName;
    PPERFECT_HASH_FILE File;
    PPERFECT_HASH_TABLE Table;

    //
    // Initialize aliases.
    //

    Table = Context->Table;
    File = *Item->FilePointer;
    ModuleBaseName = &Table->OutputDirectory->Path->BaseNameA;

    Base = (PCHAR)File->BaseAddress;
    Output = Base;

    //
    // Write Cargo.toml.
    //

    OUTPUT_RAW("# Auto-generated by Perfect Hash.\n");
    OUTPUT_RAW("[package]\n");
    OUTPUT_RAW("name = \"perfecthash_generated\"\n");
    OUTPUT_RAW("version = \"0.1.0\"\n");
    OUTPUT_RAW("edition = \"2021\"\n\n");

    OUTPUT_RAW("[lib]\n");
    OUTPUT_RAW("path = \"");
    OUTPUT_STRING(ModuleBaseName);
    OUTPUT_RAW("_RustLib.rs\"\n\n");

    OUTPUT_RAW("[[bin]]\n");
    OUTPUT_RAW("name = \"rust_test\"\n");
    OUTPUT_RAW("path = \"");
    OUTPUT_STRING(ModuleBaseName);
    OUTPUT_RAW("_RustTest.rs\"\n\n");

    OUTPUT_RAW("[[bin]]\n");
    OUTPUT_RAW("name = \"rust_bench\"\n");
    OUTPUT_RAW("path = \"");
    OUTPUT_STRING(ModuleBaseName);
    OUTPUT_RAW("_RustBench.rs\"\n\n");

    //
    // Update the number of bytes written.
    //

    File->NumberOfBytesWritten.QuadPart = RtlPointerToOffset(Base, Output);

    return S_OK;
}

// vim:set ts=8 sw=4 sts=4 tw=80 expandtab                                     :