/*++

Copyright (c) 2026 Trent Nelson <trent@trent.me>

Module Name:

    Chm01FileWorkRustTestFile.c

Abstract:

    This module implements the save file work callback routine for the Rust
    test file as part of the CHM v1 algorithm implementation for the perfect
    hash library.

--*/

#include "stdafx.h"

_Use_decl_annotations_
HRESULT
SaveRustTestFileChm01(
    PPERFECT_HASH_CONTEXT Context,
    PFILE_WORK_ITEM Item
    )
{
    PCHAR Base;
    PCHAR Output;
    PPERFECT_HASH_FILE File;

    //
    // Initialize aliases.
    //

    UNREFERENCED_PARAMETER(Context);

    File = *Item->FilePointer;

    Base = (PCHAR)File->BaseAddress;
    Output = Base;

    //
    // Write test file.
    //

    OUTPUT_RAW("// Auto-generated by Perfect Hash.\n");
    OUTPUT_RAW("use perfecthash_generated as ph;\n");
    OUTPUT_RAW("use std::process;\n\n");

    OUTPUT_RAW("fn main() {\n");
    OUTPUT_RAW("    if !ph::SUPPORTED {\n");
    OUTPUT_RAW("        println!(\"unsupported\");\n");
    OUTPUT_RAW("        return;\n");
    OUTPUT_RAW("    }\n");
    OUTPUT_RAW("    let mut seen = vec![0u8; ph::INDEX_MASK as usize + 1];\n");
    OUTPUT_RAW("    let mut count = 0usize;\n");
    OUTPUT_RAW("    for &key in ph::KEYS.iter() {\n");
    OUTPUT_RAW("        let idx = ph::index(key);\n");
    OUTPUT_RAW("        let pos = idx as usize;\n");
    OUTPUT_RAW("        if pos >= seen.len() {\n");
    OUTPUT_RAW("            eprintln!(\"index out of range: {}\", idx);\n");
    OUTPUT_RAW("            process::exit(1);\n");
    OUTPUT_RAW("        }\n");
    OUTPUT_RAW("        if seen[pos] != 0 {\n");
    OUTPUT_RAW("            eprintln!(\"collision at {}\", idx);\n");
    OUTPUT_RAW("            process::exit(1);\n");
    OUTPUT_RAW("        }\n");
    OUTPUT_RAW("        seen[pos] = 1;\n");
    OUTPUT_RAW("        count += 1;\n");
    OUTPUT_RAW("    }\n");
    OUTPUT_RAW("    if count != ph::NUMBER_OF_KEYS {\n");
    OUTPUT_RAW("        eprintln!(\"index count mismatch\");\n");
    OUTPUT_RAW("        process::exit(1);\n");
    OUTPUT_RAW("    }\n");
    OUTPUT_RAW("    println!(\"ok\");\n");
    OUTPUT_RAW("}\n");

    //
    // Update the number of bytes written.
    //

    File->NumberOfBytesWritten.QuadPart = RtlPointerToOffset(Base, Output);

    return S_OK;
}

// vim:set ts=8 sw=4 sts=4 tw=80 expandtab                                     :