//
// Auto-generated.
//

DECLSPEC_ALIGN(16)
const CHAR CompiledPerfectHashTableTestCSourceRawCStr[] =
    "\n"
    "//\n"
    "// Begin CompiledPerfectHashTableTest.c.\n"
    "//\n"
    "\n"
    "\n"
    "#ifdef _WIN32\n"
    "\n"
    "//\n"
    "// Disable global optimizations, even in release builds.  Without this, the\n"
    "// compiler does clever things with regards to optimizing our __debugbreak()\n"
    "// logic below, such that it's impossible to tell which ASSERT() triggered it.\n"
    "//\n"
    "\n"
    "#pragma optimize(\"\", off)\n"
    "\n"
    "//\n"
    "// Disable Spectre warnings.\n"
    "//\n"
    "\n"
    "#pragma warning(disable: 5045)\n"
    "\n"
    "#endif\n"
    "\n"
    "//\n"
    "// Use a custom ASSERT() macro that optionally issues a __debugbreak() based\n"
    "// on the caller's DebugBreakOnFailure boolean flag.\n"
    "//\n"
    "\n"
    "#undef ASSERT\n"
    "#define ASSERT(Condition)          \\\n"
    "    if (!(Condition)) {            \\\n"
    "        if (DebugBreakOnFailure) { \\\n"
    "            DEBUGBREAK();          \\\n"
    "        };                         \\\n"
    "        NumberOfErrors++;          \\\n"
    "    }\n"
    "\n"
    "#ifdef CPH_HAS_INDEX32X8_ROUTINE\n"
    "extern\n"
    "VOID\n"
    "CPHCALLTYPE\n"
    "INDEX32X8_ROUTINE(\n"
    "    _In_ CPHKEY Key1,\n"
    "    _In_ CPHKEY Key2,\n"
    "    _In_ CPHKEY Key3,\n"
    "    _In_ CPHKEY Key4,\n"
    "    _In_ CPHKEY Key5,\n"
    "    _In_ CPHKEY Key6,\n"
    "    _In_ CPHKEY Key7,\n"
    "    _In_ CPHKEY Key8,\n"
    "    _Out_ PCPHINDEX Index1,\n"
    "    _Out_ PCPHINDEX Index2,\n"
    "    _Out_ PCPHINDEX Index3,\n"
    "    _Out_ PCPHINDEX Index4,\n"
    "    _Out_ PCPHINDEX Index5,\n"
    "    _Out_ PCPHINDEX Index6,\n"
    "    _Out_ PCPHINDEX Index7,\n"
    "    _Out_ PCPHINDEX Index8\n"
    "    );\n"
    "#endif\n"
    "\n"
    "#ifdef CPH_HAS_INDEX32X16_ROUTINE\n"
    "extern\n"
    "VOID\n"
    "CPHCALLTYPE\n"
    "INDEX32X16_ROUTINE(\n"
    "    _In_ CPHKEY Key1,\n"
    "    _In_ CPHKEY Key2,\n"
    "    _In_ CPHKEY Key3,\n"
    "    _In_ CPHKEY Key4,\n"
    "    _In_ CPHKEY Key5,\n"
    "    _In_ CPHKEY Key6,\n"
    "    _In_ CPHKEY Key7,\n"
    "    _In_ CPHKEY Key8,\n"
    "    _In_ CPHKEY Key9,\n"
    "    _In_ CPHKEY Key10,\n"
    "    _In_ CPHKEY Key11,\n"
    "    _In_ CPHKEY Key12,\n"
    "    _In_ CPHKEY Key13,\n"
    "    _In_ CPHKEY Key14,\n"
    "    _In_ CPHKEY Key15,\n"
    "    _In_ CPHKEY Key16,\n"
    "    _Out_ PCPHINDEX Index1,\n"
    "    _Out_ PCPHINDEX Index2,\n"
    "    _Out_ PCPHINDEX Index3,\n"
    "    _Out_ PCPHINDEX Index4,\n"
    "    _Out_ PCPHINDEX Index5,\n"
    "    _Out_ PCPHINDEX Index6,\n"
    "    _Out_ PCPHINDEX Index7,\n"
    "    _Out_ PCPHINDEX Index8,\n"
    "    _Out_ PCPHINDEX Index9,\n"
    "    _Out_ PCPHINDEX Index10,\n"
    "    _Out_ PCPHINDEX Index11,\n"
    "    _Out_ PCPHINDEX Index12,\n"
    "    _Out_ PCPHINDEX Index13,\n"
    "    _Out_ PCPHINDEX Index14,\n"
    "    _Out_ PCPHINDEX Index15,\n"
    "    _Out_ PCPHINDEX Index16\n"
    "    );\n"
    "#endif\n"
    "\n"
    "DECLARE_TEST_CPH_ROUTINE()\n"
    "/*++\n"
    "\n"
    "Routine Description:\n"
    "\n"
    "    Tests a compiled perfect hash table for correctness.\n"
    "\n"
    "Arguments:\n"
    "\n"
    "    DebugBreakOnFailure - Supplies a boolean flag that indicates whether or\n"
    "        not a __debugbreak() should be issued as soon as a test fails.\n"
    "\n"
    "Return Value:\n"
    "\n"
    "    The number of failed tests.  If 0, all tests passed.\n"
    "\n"
    "--*/\n"
    "{\n"
    "    CPHINDEX Index;\n"
    "    CPHKEY Key;\n"
    "    CPHKEY Rotated;\n"
    "    CPHVALUE Value;\n"
    "    CPHVALUE Previous;\n"
    "    ULONG NumberOfErrors = 0;\n"
    "    const CPHKEY *Source;\n"
    "\n"
    "    Key = *KEYS;\n"
    "\n"
    "    //\n"
    "    // Rotate the key such that it differs from the original value, but in a\n"
    "    // way that can be easily reversed.\n"
    "    //\n"
    "\n"
    "    Rotated = ROTATE_KEY_LEFT(Key, 15);\n"
    "    ASSERT(Key == ROTATE_KEY_RIGHT(Rotated, 15));\n"
    "\n"
    "    //\n"
    "    // Verify looking up a key that hasn't been inserted returns 0 as the value.\n"
    "    //\n"
    "\n"
    "    Value = LOOKUP_ROUTINE(Key);\n"
    "    ASSERT(Value == 0);\n"
    "\n"
    "    //\n"
    "    // Verify insertion.\n"
    "    //\n"
    "\n"
    "    Previous = INSERT_ROUTINE(Key, (CPHVALUE)Rotated);\n"
    "    ASSERT(Previous == 0);\n"
    "\n"
    "    //\n"
    "    // Lookup the inserted key.\n"
    "    //\n"
    "\n"
    "    Value = LOOKUP_ROUTINE(Key);\n"
    "    ASSERT(Value == (CPHVALUE)Rotated);\n"
    "\n"
    "    //\n"
    "    // Delete the inserted key.  Returned value should be Rotated.\n"
    "    //\n"
    "\n"
    "    Value = DELETE_ROUTINE(Key);\n"
    "    ASSERT(Value == (CPHVALUE)Rotated);\n"
    "\n"
    "    //\n"
    "    // Verify a subsequent lookup returns 0.\n"
    "    //\n"
    "\n"
    "    Value = LOOKUP_ROUTINE(Key);\n"
    "    ASSERT(Value == 0);\n"
    "\n"
    "#ifdef CPH_HAS_INDEX32X8_ROUTINE\n"
    "    if (NUMBER_OF_KEYS >= 8) {\n"
    "        ULONG Lane;\n"
    "        CPHINDEX Indices[8];\n"
    "        const CPHKEY *VectorKeys = KEYS;\n"
    "\n"
    "        INDEX32X8_ROUTINE(\n"
    "            VectorKeys[0],\n"
    "            VectorKeys[1],\n"
    "            VectorKeys[2],\n"
    "            VectorKeys[3],\n"
    "            VectorKeys[4],\n"
    "            VectorKeys[5],\n"
    "            VectorKeys[6],\n"
    "            VectorKeys[7],\n"
    "            &Indices[0],\n"
    "            &Indices[1],\n"
    "            &Indices[2],\n"
    "            &Indices[3],\n"
    "            &Indices[4],\n"
    "            &Indices[5],\n"
    "            &Indices[6],\n"
    "            &Indices[7]\n"
    "        );\n"
    "\n"
    "        for (Lane = 0; Lane < 8; Lane++) {\n"
    "            Index = INDEX_ROUTINE(VectorKeys[Lane]);\n"
    "            ASSERT(Indices[Lane] == Index);\n"
    "        }\n"
    "    }\n"
    "#endif\n"
    "\n"
    "#ifdef CPH_HAS_INDEX32X16_ROUTINE\n"
    "    if (NUMBER_OF_KEYS >= 16) {\n"
    "        ULONG Lane;\n"
    "        CPHINDEX Indices[16];\n"
    "        const CPHKEY *VectorKeys = KEYS;\n"
    "\n"
    "        INDEX32X16_ROUTINE(\n"
    "            VectorKeys[0],\n"
    "            VectorKeys[1],\n"
    "            VectorKeys[2],\n"
    "            VectorKeys[3],\n"
    "            VectorKeys[4],\n"
    "            VectorKeys[5],\n"
    "            VectorKeys[6],\n"
    "            VectorKeys[7],\n"
    "            VectorKeys[8],\n"
    "            VectorKeys[9],\n"
    "            VectorKeys[10],\n"
    "            VectorKeys[11],\n"
    "            VectorKeys[12],\n"
    "            VectorKeys[13],\n"
    "            VectorKeys[14],\n"
    "            VectorKeys[15],\n"
    "            &Indices[0],\n"
    "            &Indices[1],\n"
    "            &Indices[2],\n"
    "            &Indices[3],\n"
    "            &Indices[4],\n"
    "            &Indices[5],\n"
    "            &Indices[6],\n"
    "            &Indices[7],\n"
    "            &Indices[8],\n"
    "            &Indices[9],\n"
    "            &Indices[10],\n"
    "            &Indices[11],\n"
    "            &Indices[12],\n"
    "            &Indices[13],\n"
    "            &Indices[14],\n"
    "            &Indices[15]\n"
    "        );\n"
    "\n"
    "        for (Lane = 0; Lane < 16; Lane++) {\n"
    "            Index = INDEX_ROUTINE(VectorKeys[Lane]);\n"
    "            ASSERT(Indices[Lane] == Index);\n"
    "        }\n"
    "    }\n"
    "#endif\n"
    "\n"
    "    //\n"
    "    // Loop through the entire key set and insert a rotated version of the key.\n"
    "    //\n"
    "\n"
    "    FOR_EACH_KEY {\n"
    "\n"
    "        Key = *Source++;\n"
    "        Rotated = ROTATE_KEY_LEFT(Key, 15);\n"
    "\n"
    "        Previous = INSERT_ROUTINE(Key, (CPHVALUE)Rotated);\n"
    "        ASSERT(Previous == 0);\n"
    "\n"
    "    }\n"
    "\n"
    "    //\n"
    "    // Loop through the entire set again and ensure that lookup returns the\n"
    "    // rotated version.\n"
    "    //\n"
    "\n"
    "    FOR_EACH_KEY {\n"
    "\n"
    "        Key = *Source++;\n"
    "        Rotated = ROTATE_KEY_LEFT(Key, 15);\n"
    "\n"
    "        Value = LOOKUP_ROUTINE(Key);\n"
    "        ASSERT(Value == (CPHVALUE)Rotated);\n"
    "\n"
    "    }\n"
    "\n"
    "    //\n"
    "    // Loop through again and delete everything.\n"
    "    //\n"
    "\n"
    "    FOR_EACH_KEY {\n"
    "\n"
    "        Key = *Source++;\n"
    "        Rotated = ROTATE_KEY_LEFT(Key, 15);\n"
    "\n"
    "        Previous = DELETE_ROUTINE(Key);\n"
    "        ASSERT(Previous == (CPHVALUE)Rotated);\n"
    "\n"
    "    }\n"
    "\n"
    "    //\n"
    "    // And a final loop through to confirm all lookups now return 0.\n"
    "    //\n"
    "\n"
    "    FOR_EACH_KEY {\n"
    "\n"
    "        Key = *Source++;\n"
    "\n"
    "        Value = LOOKUP_ROUTINE(Key);\n"
    "        ASSERT(Value == 0);\n"
    "\n"
    "    }\n"
    "\n"
    "    //\n"
    "    // We're finished!  Return the number of errors.\n"
    "    //\n"
    "\n"
    "    return NumberOfErrors;\n"
    "}\n"
    "\n"
    "//\n"
    "// End CompiledPerfectHashTableTest.c.\n"
    "//\n"
    "\n"
;

const STRING CompiledPerfectHashTableTestCSourceRawCString = {
    sizeof(CompiledPerfectHashTableTestCSourceRawCStr) - sizeof(CHAR),
    sizeof(CompiledPerfectHashTableTestCSourceRawCStr),
#ifdef _WIN64
    0,
#endif
    (PCHAR)&CompiledPerfectHashTableTestCSourceRawCStr,
};

#ifndef RawCString
#define RawCString (&CompiledPerfectHashTableTestCSourceRawCString)
#endif
