//
// Auto-generated.
//

DECLSPEC_ALIGN(16)
const CHAR CompiledPerfectHashTableTypesPreCHeaderRawCStr[] =
    "\n"
    "//\n"
    "// Begin CompiledPerfectHashTableTypesPre.h.\n"
    "//\n"
    "\n"
    "\n"
    "#ifndef BASETYPES\n"
    "\n"
    "//\n"
    "// Define basic NT types.\n"
    "//\n"
    "\n"
    "typedef int BOOL;\n"
    "typedef char BOOLEAN;\n"
    "typedef char CHAR;\n"
    "typedef short WCHAR;\n"
    "typedef unsigned char BYTE;\n"
    "typedef BYTE *PBYTE;\n"
    "typedef short SHORT;\n"
    "typedef short *PSHORT;\n"
    "typedef unsigned short USHORT;\n"
    "typedef unsigned short *PUSHORT;\n"
    "typedef long long LONGLONG;\n"
    "typedef long long *PLONGLONG;\n"
    "typedef unsigned long long ULONGLONG;\n"
    "typedef unsigned long long *PULONGLONG;\n"
    "typedef void *PVOID;\n"
    "\n"
    "#define VOID void\n"
    "\n"
    "#ifdef _WIN32\n"
    "typedef long LONG;\n"
    "typedef long *PLONG;\n"
    "typedef unsigned long ULONG;\n"
    "typedef unsigned long *PULONG;\n"
    "#elif defined(__linux__) || defined(__APPLE__)\n"
    "typedef int LONG;\n"
    "typedef int *PLONG;\n"
    "typedef unsigned int ULONG;\n"
    "typedef unsigned int *PULONG;\n"
    "#endif\n"
    "\n"
    "#define TRUE 1\n"
    "#define FALSE 0\n"
    "\n"
    "#define BASETYPES\n"
    "\n"
    "//\n"
    "// Disable the anonymous union/struct warning.\n"
    "//\n"
    "\n"
    "#ifdef _WIN32\n"
    "#pragma warning(push)\n"
    "#pragma warning(disable: 4201 4094)\n"
    "#endif\n"
    "\n"
    "typedef union _LARGE_INTEGER {\n"
    "    struct {\n"
    "        ULONG LowPart;\n"
    "        LONG HighPart;\n"
    "    };\n"
    "    LONGLONG QuadPart;\n"
    "} LARGE_INTEGER;\n"
    "typedef LARGE_INTEGER *PLARGE_INTEGER;\n"
    "\n"
    "typedef union _ULARGE_INTEGER {\n"
    "    struct {\n"
    "        ULONG LowPart;\n"
    "        ULONG HighPart;\n"
    "    };\n"
    "    ULONGLONG QuadPart;\n"
    "} ULARGE_INTEGER;\n"
    "typedef ULARGE_INTEGER *PULARGE_INTEGER;\n"
    "\n"
    "typedef union ULONG_BYTES {\n"
    "    struct {\n"
    "        BYTE Byte1;\n"
    "        BYTE Byte2;\n"
    "        BYTE Byte3;\n"
    "        BYTE Byte4;\n"
    "    };\n"
    "\n"
    "    struct {\n"
    "        CHAR Char1;\n"
    "        CHAR Char2;\n"
    "        CHAR Char3;\n"
    "        CHAR Char4;\n"
    "    };\n"
    "\n"
    "    struct {\n"
    "        SHORT Word1;\n"
    "        SHORT Word2;\n"
    "    };\n"
    "\n"
    "    struct {\n"
    "        USHORT UWord1;\n"
    "        USHORT UWord2;\n"
    "    };\n"
    "\n"
    "    LONG AsLong;\n"
    "    ULONG AsULong;\n"
    "} ULONG_BYTES;\n"
    "typedef ULONG_BYTES *PULONG_BYTES;\n"
    "\n"
    "typedef union _ULONG_INTEGER {\n"
    "    struct {\n"
    "        USHORT  LowPart;\n"
    "        USHORT  HighPart;\n"
    "    };\n"
    "    ULONG   LongPart;\n"
    "\n"
    "} ULONG_INTEGER, *PULONG_INTEGER;\n"
    "\n"
    "typedef union _LONG_INTEGER {\n"
    "    struct {\n"
    "        USHORT  LowPart;\n"
    "        SHORT   HighPart;\n"
    "    };\n"
    "    LONG   LongPart;\n"
    "} LONG_INTEGER, *PLONG_INTEGER;\n"
    "\n"
    "typedef union _USHORT_INTEGER {\n"
    "    struct {\n"
    "        BYTE  LowPart;\n"
    "        BYTE  HighPart;\n"
    "    };\n"
    "    USHORT   ShortPart;\n"
    "} USHORT_INTEGER, *PUSHORT_INTEGER;\n"
    "\n"
    "typedef union _SHORT_INTEGER {\n"
    "    struct {\n"
    "        CHAR  LowPart;\n"
    "        CHAR  HighPart;\n"
    "    };\n"
    "    SHORT   ShortPart;\n"
    "} SHORT_INTEGER, *PSHORT_INTEGER;\n"
    "\n"
    "typedef union _WIDE_CHARACTER {\n"
    "    struct {\n"
    "        CHAR  LowPart;\n"
    "        CHAR  HighPart;\n"
    "    };\n"
    "    WCHAR WidePart;\n"
    "} WIDE_CHARACTER, *PWIDE_CHARACTER;\n"
    "\n"
    "#ifdef _WIN32\n"
    "#pragma warning(pop)\n"
    "#endif\n"
    "\n"
    "#endif\n"
    "\n"
    "//\n"
    "// End CompiledPerfectHashTableTypesPre.h.\n"
    "//\n"
    "\n"
;

const STRING CompiledPerfectHashTableTypesPreCHeaderRawCString = {
    sizeof(CompiledPerfectHashTableTypesPreCHeaderRawCStr) - sizeof(CHAR),
    sizeof(CompiledPerfectHashTableTypesPreCHeaderRawCStr),
#ifdef _WIN64
    0,
#endif
    (PCHAR)&CompiledPerfectHashTableTypesPreCHeaderRawCStr,
};

#ifndef RawCString
#define RawCString (&CompiledPerfectHashTableTypesPreCHeaderRawCString)
#endif
