//
// Auto-generated.
//

DECLSPEC_ALIGN(16)
const CHAR CompiledPerfectHashTableChm01IndexMulshrolate1RXAndCSourceRawCStr[] =
    "\n"
    "//\n"
    "// Begin CompiledPerfectHashTableChm01IndexMulshrolate1RXAnd.c.\n"
    "//\n"
    "\n"
    "#define CPH_M1RX_INDEX32X8_ROUTINE_NAME(T) CompiledPerfectHash_##T##_Index32x8\n"
    "#define CPH_M1RX_INDEX32X16_ROUTINE_NAME(T) CompiledPerfectHash_##T##_Index32x16\n"
    "\n"
    "#define EXPAND_M1RX_INDEX32X8_ROUTINE_NAME(T) CPH_M1RX_INDEX32X8_ROUTINE_NAME(T)\n"
    "#define EXPAND_M1RX_INDEX32X16_ROUTINE_NAME(T) CPH_M1RX_INDEX32X16_ROUTINE_NAME(T)\n"
    "\n"
    "#define INDEX32X8_ROUTINE EXPAND_M1RX_INDEX32X8_ROUTINE_NAME(CPH_TABLENAME)\n"
    "#define INDEX32X16_ROUTINE EXPAND_M1RX_INDEX32X16_ROUTINE_NAME(CPH_TABLENAME)\n"
    "\n"
    "#define CPH_HAS_INDEX32X8_ROUTINE 1\n"
    "#define CPH_HAS_INDEX32X16_ROUTINE 1\n"
    "\n"
    "DECLARE_INDEX_ROUTINE()\n"
    "{\n"
    "    CPHINDEX Index;\n"
    "    CPHDKEY Vertex1;\n"
    "    CPHDKEY Vertex2;\n"
    "    CPHDKEY DownsizedKey;\n"
    "\n"
    "    //IACA_VC_START();\n"
    "\n"
    "    DownsizedKey = DOWNSIZE_KEY(Key);\n"
    "\n"
    "    Vertex1 = DownsizedKey * SEED1;\n"
    "    Vertex1 = RotateRight32(Vertex1, SEED3_BYTE2);\n"
    "    Vertex1 = Vertex1 >> SEED3_BYTE1;\n"
    "    Vertex1 = TABLE_DATA[Vertex1];\n"
    "\n"
    "    Vertex2 = DownsizedKey * SEED2;\n"
    "    Vertex2 = Vertex2 >> SEED3_BYTE1;\n"
    "    Vertex2 = TABLE_DATA[Vertex2];\n"
    "\n"
    "    Index = (CPHINDEX)((Vertex1 + Vertex2) & INDEX_MASK);\n"
    "\n"
    "    //IACA_VC_END();\n"
    "\n"
    "    return Index;\n"
    "}\n"
    "\n"
    "#ifndef CPH_INLINE_ROUTINES\n"
    "\n"
    "#if defined(_M_X64) || defined(__x86_64__) || defined(__i386__)\n"
    "#include <immintrin.h>\n"
    "#endif\n"
    "\n"
    "#if (defined(__clang__) || defined(__GNUC__)) && \\\n"
    "    (defined(__x86_64__) || defined(__i386__))\n"
    "#define CPH_M1RX_HAS_TARGET_ATTR 1\n"
    "#endif\n"
    "\n"
    "#if defined(CPH_M1RX_HAS_TARGET_ATTR) || defined(__AVX2__)\n"
    "#define CPH_M1RX_CAN_BUILD_AVX2 1\n"
    "#endif\n"
    "\n"
    "#if defined(CPH_M1RX_HAS_TARGET_ATTR) || defined(__AVX512F__)\n"
    "#define CPH_M1RX_CAN_BUILD_AVX512 1\n"
    "#endif\n"
    "\n"
    "#if defined(CPH_M1RX_HAS_TARGET_ATTR)\n"
    "#define CPH_M1RX_TARGET_AVX2 __attribute__((target(\"avx2\")))\n"
    "#define CPH_M1RX_TARGET_AVX512 __attribute__((target(\"avx512f\")))\n"
    "#else\n"
    "#define CPH_M1RX_TARGET_AVX2\n"
    "#define CPH_M1RX_TARGET_AVX512\n"
    "#endif\n"
    "\n"
    "FORCEINLINE\n"
    "CPHINDEX\n"
    "CphMulshrolate1RXFinalizeIndex(\n"
    "    CPHDKEY Vertex1,\n"
    "    CPHDKEY Vertex2\n"
    "    )\n"
    "{\n"
    "    CPHDKEY Assigned1;\n"
    "    CPHDKEY Assigned2;\n"
    "\n"
    "    Assigned1 = TABLE_DATA[Vertex1];\n"
    "    Assigned2 = TABLE_DATA[Vertex2];\n"
    "\n"
    "    return (CPHINDEX)((Assigned1 + Assigned2) & INDEX_MASK);\n"
    "}\n"
    "\n"
    "FORCEINLINE\n"
    "VOID\n"
    "CphMulshrolate1RXComputeVerticesScalar(\n"
    "    _In_reads_(Count) PULONG Keys,\n"
    "    _Out_writes_(Count) PCPHDKEY Vertex1,\n"
    "    _Out_writes_(Count) PCPHDKEY Vertex2,\n"
    "    _In_ ULONG Count\n"
    "    )\n"
    "{\n"
    "    ULONG Index;\n"
    "\n"
    "    for (Index = 0; Index < Count; Index++) {\n"
    "        CPHDKEY Value1;\n"
    "        CPHDKEY Value2;\n"
    "\n"
    "        Value1 = Keys[Index] * SEED1;\n"
    "        Value1 = RotateRight32(Value1, SEED3_BYTE2);\n"
    "        Value1 = Value1 >> SEED3_BYTE1;\n"
    "\n"
    "        Value2 = Keys[Index] * SEED2;\n"
    "        Value2 = Value2 >> SEED3_BYTE1;\n"
    "\n"
    "        Vertex1[Index] = Value1;\n"
    "        Vertex2[Index] = Value2;\n"
    "    }\n"
    "}\n"
    "\n"
    "#if defined(CPH_M1RX_CAN_BUILD_AVX2)\n"
    "static CPH_M1RX_TARGET_AVX2\n"
    "VOID\n"
    "CphMulshrolate1RXComputeVertices8Avx2(\n"
    "    _In_reads_(8) PULONG Keys,\n"
    "    _Out_writes_(8) PCPHDKEY Vertex1,\n"
    "    _Out_writes_(8) PCPHDKEY Vertex2\n"
    "    )\n"
    "{\n"
    "    const __m256i KeysYmm = _mm256_loadu_si256((const __m256i *)(const VOID *)Keys);\n"
    "    const __m256i Seed1Ymm = _mm256_set1_epi32((int)SEED1);\n"
    "    const __m256i Seed2Ymm = _mm256_set1_epi32((int)SEED2);\n"
    "\n"
    "    const __m256i RotateYmm = _mm256_set1_epi32((int)(SEED3_BYTE2 & 31));\n"
    "    const __m256i RotateInverseYmm =\n"
    "        _mm256_set1_epi32((int)((32 - (SEED3_BYTE2 & 31)) & 31));\n"
    "    const __m256i ShiftYmm = _mm256_set1_epi32((int)(SEED3_BYTE1 & 31));\n"
    "\n"
    "    __m256i Value1Ymm = _mm256_mullo_epi32(KeysYmm, Seed1Ymm);\n"
    "    __m256i Value2Ymm = _mm256_mullo_epi32(KeysYmm, Seed2Ymm);\n"
    "\n"
    "    Value1Ymm = _mm256_or_si256(\n"
    "        _mm256_srlv_epi32(Value1Ymm, RotateYmm),\n"
    "        _mm256_sllv_epi32(Value1Ymm, RotateInverseYmm)\n"
    "    );\n"
    "\n"
    "    Value1Ymm = _mm256_srlv_epi32(Value1Ymm, ShiftYmm);\n"
    "    Value2Ymm = _mm256_srlv_epi32(Value2Ymm, ShiftYmm);\n"
    "\n"
    "    _mm256_storeu_si256((__m256i *)(VOID *)Vertex1, Value1Ymm);\n"
    "    _mm256_storeu_si256((__m256i *)(VOID *)Vertex2, Value2Ymm);\n"
    "}\n"
    "#endif\n"
    "\n"
    "#if defined(CPH_M1RX_CAN_BUILD_AVX512)\n"
    "static CPH_M1RX_TARGET_AVX512\n"
    "VOID\n"
    "CphMulshrolate1RXComputeVertices16Avx512(\n"
    "    _In_reads_(16) PULONG Keys,\n"
    "    _Out_writes_(16) PCPHDKEY Vertex1,\n"
    "    _Out_writes_(16) PCPHDKEY Vertex2\n"
    "    )\n"
    "{\n"
    "    const __m512i KeysZmm = _mm512_loadu_si512((const VOID *)Keys);\n"
    "    const __m512i Seed1Zmm = _mm512_set1_epi32((int)SEED1);\n"
    "    const __m512i Seed2Zmm = _mm512_set1_epi32((int)SEED2);\n"
    "\n"
    "    const __m512i RotateZmm = _mm512_set1_epi32((int)(SEED3_BYTE2 & 31));\n"
    "    const __m512i RotateInverseZmm =\n"
    "        _mm512_set1_epi32((int)((32 - (SEED3_BYTE2 & 31)) & 31));\n"
    "    const __m512i ShiftZmm = _mm512_set1_epi32((int)(SEED3_BYTE1 & 31));\n"
    "\n"
    "    __m512i Value1Zmm = _mm512_mullo_epi32(KeysZmm, Seed1Zmm);\n"
    "    __m512i Value2Zmm = _mm512_mullo_epi32(KeysZmm, Seed2Zmm);\n"
    "\n"
    "    Value1Zmm = _mm512_or_si512(\n"
    "        _mm512_srlv_epi32(Value1Zmm, RotateZmm),\n"
    "        _mm512_sllv_epi32(Value1Zmm, RotateInverseZmm)\n"
    "    );\n"
    "\n"
    "    Value1Zmm = _mm512_srlv_epi32(Value1Zmm, ShiftZmm);\n"
    "    Value2Zmm = _mm512_srlv_epi32(Value2Zmm, ShiftZmm);\n"
    "\n"
    "    _mm512_storeu_si512((VOID *)Vertex1, Value1Zmm);\n"
    "    _mm512_storeu_si512((VOID *)Vertex2, Value2Zmm);\n"
    "}\n"
    "#endif\n"
    "\n"
    "FORCEINLINE\n"
    "BOOLEAN\n"
    "CphMulshrolate1RXCanUseAvx2(\n"
    "    VOID\n"
    "    )\n"
    "{\n"
    "#if defined(CPH_M1RX_CAN_BUILD_AVX2)\n"
    "#if defined(CPH_M1RX_HAS_TARGET_ATTR)\n"
    "    return (__builtin_cpu_supports(\"avx2\") != 0);\n"
    "#else\n"
    "    return TRUE;\n"
    "#endif\n"
    "#else\n"
    "    return FALSE;\n"
    "#endif\n"
    "}\n"
    "\n"
    "FORCEINLINE\n"
    "BOOLEAN\n"
    "CphMulshrolate1RXCanUseAvx512(\n"
    "    VOID\n"
    "    )\n"
    "{\n"
    "#if defined(CPH_M1RX_CAN_BUILD_AVX512)\n"
    "#if defined(CPH_M1RX_HAS_TARGET_ATTR)\n"
    "    return (__builtin_cpu_supports(\"avx512f\") != 0);\n"
    "#else\n"
    "    return TRUE;\n"
    "#endif\n"
    "#else\n"
    "    return FALSE;\n"
    "#endif\n"
    "}\n"
    "\n"
    "CPHAPI\n"
    "VOID\n"
    "CPHCALLTYPE\n"
    "INDEX32X8_ROUTINE(\n"
    "    _In_ CPHKEY Key1,\n"
    "    _In_ CPHKEY Key2,\n"
    "    _In_ CPHKEY Key3,\n"
    "    _In_ CPHKEY Key4,\n"
    "    _In_ CPHKEY Key5,\n"
    "    _In_ CPHKEY Key6,\n"
    "    _In_ CPHKEY Key7,\n"
    "    _In_ CPHKEY Key8,\n"
    "    _Out_ PCPHINDEX Index1,\n"
    "    _Out_ PCPHINDEX Index2,\n"
    "    _Out_ PCPHINDEX Index3,\n"
    "    _Out_ PCPHINDEX Index4,\n"
    "    _Out_ PCPHINDEX Index5,\n"
    "    _Out_ PCPHINDEX Index6,\n"
    "    _Out_ PCPHINDEX Index7,\n"
    "    _Out_ PCPHINDEX Index8\n"
    "    )\n"
    "{\n"
    "    ULONG Keys[8];\n"
    "    CPHDKEY Vertex1[8];\n"
    "    CPHDKEY Vertex2[8];\n"
    "\n"
    "    Keys[0] = DOWNSIZE_KEY(Key1);\n"
    "    Keys[1] = DOWNSIZE_KEY(Key2);\n"
    "    Keys[2] = DOWNSIZE_KEY(Key3);\n"
    "    Keys[3] = DOWNSIZE_KEY(Key4);\n"
    "    Keys[4] = DOWNSIZE_KEY(Key5);\n"
    "    Keys[5] = DOWNSIZE_KEY(Key6);\n"
    "    Keys[6] = DOWNSIZE_KEY(Key7);\n"
    "    Keys[7] = DOWNSIZE_KEY(Key8);\n"
    "\n"
    "    if (CphMulshrolate1RXCanUseAvx2()) {\n"
    "#if defined(CPH_M1RX_CAN_BUILD_AVX2)\n"
    "        CphMulshrolate1RXComputeVertices8Avx2(Keys, Vertex1, Vertex2);\n"
    "#endif\n"
    "    } else {\n"
    "        CphMulshrolate1RXComputeVerticesScalar(Keys, Vertex1, Vertex2, 8);\n"
    "    }\n"
    "\n"
    "    *Index1 = CphMulshrolate1RXFinalizeIndex(Vertex1[0], Vertex2[0]);\n"
    "    *Index2 = CphMulshrolate1RXFinalizeIndex(Vertex1[1], Vertex2[1]);\n"
    "    *Index3 = CphMulshrolate1RXFinalizeIndex(Vertex1[2], Vertex2[2]);\n"
    "    *Index4 = CphMulshrolate1RXFinalizeIndex(Vertex1[3], Vertex2[3]);\n"
    "    *Index5 = CphMulshrolate1RXFinalizeIndex(Vertex1[4], Vertex2[4]);\n"
    "    *Index6 = CphMulshrolate1RXFinalizeIndex(Vertex1[5], Vertex2[5]);\n"
    "    *Index7 = CphMulshrolate1RXFinalizeIndex(Vertex1[6], Vertex2[6]);\n"
    "    *Index8 = CphMulshrolate1RXFinalizeIndex(Vertex1[7], Vertex2[7]);\n"
    "}\n"
    "\n"
    "CPHAPI\n"
    "VOID\n"
    "CPHCALLTYPE\n"
    "INDEX32X16_ROUTINE(\n"
    "    _In_ CPHKEY Key1,\n"
    "    _In_ CPHKEY Key2,\n"
    "    _In_ CPHKEY Key3,\n"
    "    _In_ CPHKEY Key4,\n"
    "    _In_ CPHKEY Key5,\n"
    "    _In_ CPHKEY Key6,\n"
    "    _In_ CPHKEY Key7,\n"
    "    _In_ CPHKEY Key8,\n"
    "    _In_ CPHKEY Key9,\n"
    "    _In_ CPHKEY Key10,\n"
    "    _In_ CPHKEY Key11,\n"
    "    _In_ CPHKEY Key12,\n"
    "    _In_ CPHKEY Key13,\n"
    "    _In_ CPHKEY Key14,\n"
    "    _In_ CPHKEY Key15,\n"
    "    _In_ CPHKEY Key16,\n"
    "    _Out_ PCPHINDEX Index1,\n"
    "    _Out_ PCPHINDEX Index2,\n"
    "    _Out_ PCPHINDEX Index3,\n"
    "    _Out_ PCPHINDEX Index4,\n"
    "    _Out_ PCPHINDEX Index5,\n"
    "    _Out_ PCPHINDEX Index6,\n"
    "    _Out_ PCPHINDEX Index7,\n"
    "    _Out_ PCPHINDEX Index8,\n"
    "    _Out_ PCPHINDEX Index9,\n"
    "    _Out_ PCPHINDEX Index10,\n"
    "    _Out_ PCPHINDEX Index11,\n"
    "    _Out_ PCPHINDEX Index12,\n"
    "    _Out_ PCPHINDEX Index13,\n"
    "    _Out_ PCPHINDEX Index14,\n"
    "    _Out_ PCPHINDEX Index15,\n"
    "    _Out_ PCPHINDEX Index16\n"
    "    )\n"
    "{\n"
    "    ULONG Keys[16];\n"
    "    CPHDKEY Vertex1[16];\n"
    "    CPHDKEY Vertex2[16];\n"
    "\n"
    "    Keys[0] = DOWNSIZE_KEY(Key1);\n"
    "    Keys[1] = DOWNSIZE_KEY(Key2);\n"
    "    Keys[2] = DOWNSIZE_KEY(Key3);\n"
    "    Keys[3] = DOWNSIZE_KEY(Key4);\n"
    "    Keys[4] = DOWNSIZE_KEY(Key5);\n"
    "    Keys[5] = DOWNSIZE_KEY(Key6);\n"
    "    Keys[6] = DOWNSIZE_KEY(Key7);\n"
    "    Keys[7] = DOWNSIZE_KEY(Key8);\n"
    "    Keys[8] = DOWNSIZE_KEY(Key9);\n"
    "    Keys[9] = DOWNSIZE_KEY(Key10);\n"
    "    Keys[10] = DOWNSIZE_KEY(Key11);\n"
    "    Keys[11] = DOWNSIZE_KEY(Key12);\n"
    "    Keys[12] = DOWNSIZE_KEY(Key13);\n"
    "    Keys[13] = DOWNSIZE_KEY(Key14);\n"
    "    Keys[14] = DOWNSIZE_KEY(Key15);\n"
    "    Keys[15] = DOWNSIZE_KEY(Key16);\n"
    "\n"
    "    if (CphMulshrolate1RXCanUseAvx512()) {\n"
    "#if defined(CPH_M1RX_CAN_BUILD_AVX512)\n"
    "        CphMulshrolate1RXComputeVertices16Avx512(Keys, Vertex1, Vertex2);\n"
    "#endif\n"
    "    } else {\n"
    "        CphMulshrolate1RXComputeVerticesScalar(Keys, Vertex1, Vertex2, 16);\n"
    "    }\n"
    "\n"
    "    *Index1 = CphMulshrolate1RXFinalizeIndex(Vertex1[0], Vertex2[0]);\n"
    "    *Index2 = CphMulshrolate1RXFinalizeIndex(Vertex1[1], Vertex2[1]);\n"
    "    *Index3 = CphMulshrolate1RXFinalizeIndex(Vertex1[2], Vertex2[2]);\n"
    "    *Index4 = CphMulshrolate1RXFinalizeIndex(Vertex1[3], Vertex2[3]);\n"
    "    *Index5 = CphMulshrolate1RXFinalizeIndex(Vertex1[4], Vertex2[4]);\n"
    "    *Index6 = CphMulshrolate1RXFinalizeIndex(Vertex1[5], Vertex2[5]);\n"
    "    *Index7 = CphMulshrolate1RXFinalizeIndex(Vertex1[6], Vertex2[6]);\n"
    "    *Index8 = CphMulshrolate1RXFinalizeIndex(Vertex1[7], Vertex2[7]);\n"
    "    *Index9 = CphMulshrolate1RXFinalizeIndex(Vertex1[8], Vertex2[8]);\n"
    "    *Index10 = CphMulshrolate1RXFinalizeIndex(Vertex1[9], Vertex2[9]);\n"
    "    *Index11 = CphMulshrolate1RXFinalizeIndex(Vertex1[10], Vertex2[10]);\n"
    "    *Index12 = CphMulshrolate1RXFinalizeIndex(Vertex1[11], Vertex2[11]);\n"
    "    *Index13 = CphMulshrolate1RXFinalizeIndex(Vertex1[12], Vertex2[12]);\n"
    "    *Index14 = CphMulshrolate1RXFinalizeIndex(Vertex1[13], Vertex2[13]);\n"
    "    *Index15 = CphMulshrolate1RXFinalizeIndex(Vertex1[14], Vertex2[14]);\n"
    "    *Index16 = CphMulshrolate1RXFinalizeIndex(Vertex1[15], Vertex2[15]);\n"
    "}\n"
    "\n"
    "DECLARE_INDEX_IACA_ROUTINE()\n"
    "{\n"
    "    CPHINDEX Index;\n"
    "    CPHDKEY Vertex1;\n"
    "    CPHDKEY Vertex2;\n"
    "    CPHDKEY DownsizedKey;\n"
    "\n"
    "    IACA_VC_START();\n"
    "\n"
    "    DownsizedKey = DOWNSIZE_KEY(Key);\n"
    "\n"
    "    Vertex1 = DownsizedKey * SEED1;\n"
    "    Vertex1 = RotateRight32(Vertex1, SEED3_BYTE2);\n"
    "    Vertex1 = Vertex1 >> SEED3_BYTE1;\n"
    "    Vertex1 = TABLE_DATA[Vertex1];\n"
    "\n"
    "    Vertex2 = DownsizedKey * SEED2;\n"
    "    Vertex2 = Vertex2 >> SEED3_BYTE1;\n"
    "    Vertex2 = TABLE_DATA[Vertex2];\n"
    "\n"
    "    Index = (CPHINDEX)((Vertex1 + Vertex2) & INDEX_MASK);\n"
    "\n"
    "    IACA_VC_END();\n"
    "\n"
    "    return Index;\n"
    "}\n"
    "\n"
    "#endif\n"
    "\n"
    "//\n"
    "// End CompiledPerfectHashTableChm01IndexMulshrolate1RXAnd.c.\n"
    "//\n"
    "\n"
;

const STRING CompiledPerfectHashTableChm01IndexMulshrolate1RXAndCSourceRawCString = {
    sizeof(CompiledPerfectHashTableChm01IndexMulshrolate1RXAndCSourceRawCStr) - sizeof(CHAR),
    sizeof(CompiledPerfectHashTableChm01IndexMulshrolate1RXAndCSourceRawCStr),
#ifdef _WIN64
    0,
#endif
    (PCHAR)&CompiledPerfectHashTableChm01IndexMulshrolate1RXAndCSourceRawCStr,
};

#ifndef RawCString
#define RawCString (&CompiledPerfectHashTableChm01IndexMulshrolate1RXAndCSourceRawCString)
#endif
