//
// Auto-generated.
//

DECLSPEC_ALIGN(16)
const CHAR CompiledPerfectHashTableBenchmarkFullCSourceRawCStr[] =
    "\n"
    "//\n"
    "// Begin CompiledPerfectHashTableBenchmarkFull.c.\n"
    "//\n"
    "\n"
    "\n"
    "DECLARE_BENCHMARK_FULL_CPH_ROUTINE()\n"
    "{\n"
    "    ULONG Count;\n"
    "    CPHKEY Key;\n"
    "    CPHKEY Rotated;\n"
    "    CPHINDEX Index;\n"
    "    CPHVALUE Value = 0;\n"
    "    CPHVALUE Previous;\n"
    "    ULONG Best = (ULONG)-1;\n"
    "    ULONG Attempts = 100;\n"
    "    const ULONG Iterations = 10;\n"
    "    const CPHKEY *Source;\n"
    "    LARGE_INTEGER Start;\n"
    "    LARGE_INTEGER End;\n"
    "    LARGE_INTEGER Delta;\n"
    "\n"
    "    if (Seconds) {\n"
    "\n"
    "        while (!CtrlCPressed) {\n"
    "\n"
    "            CphQueryPerformanceCounter(&Start);\n"
    "\n"
    "            for (Count = Iterations; Count != 0; Count--) {\n"
    "\n"
    "                //\n"
    "                // Loop through the entire key set and insert a rotated version\n"
    "                // of the key.\n"
    "                //\n"
    "\n"
    "                FOR_EACH_KEY {\n"
    "                    Key = *Source++;\n"
    "                    Rotated = ROTATE_KEY_LEFT(Key, 15);\n"
    "                    Previous = INSERT_ROUTINE(Key, (CPHVALUE)Rotated);\n"
    "                }\n"
    "\n"
    "                //\n"
    "                // Loop through the entire set again and ensure that lookup\n"
    "                // returns the rotated version.\n"
    "                //\n"
    "\n"
    "                FOR_EACH_KEY {\n"
    "                    Key = *Source++;\n"
    "                    Value = LOOKUP_ROUTINE(Key);\n"
    "                }\n"
    "\n"
    "                //\n"
    "                // Loop through again and delete everything.\n"
    "                //\n"
    "\n"
    "                FOR_EACH_KEY {\n"
    "                    Key = *Source++;\n"
    "                    Previous = DELETE_ROUTINE(Key);\n"
    "                }\n"
    "\n"
    "            }\n"
    "\n"
    "            CphQueryPerformanceCounter(&End);\n"
    "\n"
    "            Delta.QuadPart = End.QuadPart - Start.QuadPart;\n"
    "\n"
    "            if (Delta.LowPart < Best) {\n"
    "                Best = Delta.LowPart;\n"
    "            }\n"
    "        }\n"
    "\n"
    "    } else {\n"
    "\n"
    "        while (Attempts--) {\n"
    "\n"
    "            CphQueryPerformanceCounter(&Start);\n"
    "\n"
    "            for (Count = Iterations; Count != 0; Count--) {\n"
    "\n"
    "                //\n"
    "                // Loop through the entire key set and insert a rotated version\n"
    "                // of the key.\n"
    "                //\n"
    "\n"
    "                FOR_EACH_KEY {\n"
    "                    Key = *Source++;\n"
    "                    Rotated = ROTATE_KEY_LEFT(Key, 15);\n"
    "                    Previous = INSERT_ROUTINE(Key, (CPHVALUE)Rotated);\n"
    "                }\n"
    "\n"
    "                //\n"
    "                // Loop through the entire set again and ensure that lookup\n"
    "                // returns the rotated version.\n"
    "                //\n"
    "\n"
    "                FOR_EACH_KEY {\n"
    "                    Key = *Source++;\n"
    "                    Value = LOOKUP_ROUTINE(Key);\n"
    "                }\n"
    "\n"
    "                //\n"
    "                // Loop through again and delete everything.\n"
    "                //\n"
    "\n"
    "                FOR_EACH_KEY {\n"
    "                    Key = *Source++;\n"
    "                    Previous = DELETE_ROUTINE(Key);\n"
    "                }\n"
    "            }\n"
    "\n"
    "            CphQueryPerformanceCounter(&End);\n"
    "\n"
    "            Delta.QuadPart = End.QuadPart - Start.QuadPart;\n"
    "\n"
    "            if (Delta.LowPart < Best) {\n"
    "                Best = Delta.LowPart;\n"
    "            }\n"
    "\n"
    "        }\n"
    "\n"
    "    }\n"
    "\n"
    "    return Best;\n"
    "}\n"
    "\n"
    "// vim:set ts=8 sw=4 sts=4 tw=80 expandtab                                     :\n"
    "\n"
    "//\n"
    "// End CompiledPerfectHashTableBenchmarkFull.c.\n"
    "//\n"
    "\n"
;

const STRING CompiledPerfectHashTableBenchmarkFullCSourceRawCString = {
    sizeof(CompiledPerfectHashTableBenchmarkFullCSourceRawCStr) - sizeof(CHAR),
    sizeof(CompiledPerfectHashTableBenchmarkFullCSourceRawCStr),
#ifdef _WIN64
    0,
#endif
    (PCHAR)&CompiledPerfectHashTableBenchmarkFullCSourceRawCStr,
};

#ifndef RawCString
#define RawCString (&CompiledPerfectHashTableBenchmarkFullCSourceRawCString)
#endif
