//
// Auto-generated.
//

DECLSPEC_ALIGN(16)
const CHAR no_sal2CHeaderRawCStr[] =
    "    \n"
    "/***\n"
    "*       no_sal2.h - renders the SAL annotations for documenting APIs harmless.\n"
    "*\n"
    "*       Copyright (c) Microsoft Corporation. All rights reserved.\n"
    "*\n"
    "*Purpose:\n"
    "*       sal.h provides a set of SAL2 annotations to describe how a function uses its\n"
    "*       parameters - the assumptions it makes about them, and the guarantees it makes\n"
    "*       upon finishing. This file redefines all those annotation macros to be harmless.\n"
    "*       It is designed for use in down-level build environments where the tooling may\n"
    "*       be unhappy with the standard SAL2 macro definitions.\n"
    "*\n"
    "*       [Public]\n"
    "*\n"
    "****/\n"
    "\n"
    "#ifndef _NO_SAL_2_H_\n"
    "#define _NO_SAL_2_H_\n"
    "\n"
    "#ifdef _When_\n"
    "#undef _When_\n"
    "#endif\n"
    "#define _When_(c,a)\n"
    "#ifdef _At_\n"
    "#undef _At_\n"
    "#endif\n"
    "#define _At_(t,a)\n"
    "#ifdef _At_buffer_\n"
    "#undef _At_buffer_\n"
    "#endif\n"
    "#define _At_buffer_(t,i,c,a)\n"
    "#ifdef _Group_\n"
    "#undef _Group_\n"
    "#endif\n"
    "#define _Group_(a)\n"
    "#ifdef _Pre_\n"
    "#undef _Pre_\n"
    "#endif\n"
    "#define _Pre_\n"
    "#ifdef _Post_\n"
    "#undef _Post_\n"
    "#endif\n"
    "#define _Post_\n"
    "#ifdef _Deref_\n"
    "#undef _Deref_\n"
    "#endif\n"
    "#define _Deref_\n"
    "#ifdef _Null_\n"
    "#undef _Null_\n"
    "#endif\n"
    "#define _Null_\n"
    "#ifdef _Notnull_\n"
    "#undef _Notnull_\n"
    "#endif\n"
    "#define _Notnull_\n"
    "#ifdef _Maybenull_\n"
    "#undef _Maybenull_\n"
    "#endif\n"
    "#define _Maybenull_\n"
    "#ifdef _Const_\n"
    "#undef _Const_\n"
    "#endif\n"
    "#define _Const_\n"
    "#ifdef _Check_return_\n"
    "#undef _Check_return_\n"
    "#endif\n"
    "#define _Check_return_\n"
    "#ifdef _Must_inspect_result_\n"
    "#undef _Must_inspect_result_\n"
    "#endif\n"
    "#define _Must_inspect_result_\n"
    "#ifdef _Pre_satisfies_\n"
    "#undef _Pre_satisfies_\n"
    "#endif\n"
    "#define _Pre_satisfies_(e)\n"
    "#ifdef _Post_satisfies_\n"
    "#undef _Post_satisfies_\n"
    "#endif\n"
    "#define _Post_satisfies_(e)\n"
    "#ifdef _Writable_elements_\n"
    "#undef _Writable_elements_\n"
    "#endif\n"
    "#define _Writable_elements_(s)\n"
    "#ifdef _Writable_bytes_\n"
    "#undef _Writable_bytes_\n"
    "#endif\n"
    "#define _Writable_bytes_(s)\n"
    "#ifdef _Readable_elements_\n"
    "#undef _Readable_elements_\n"
    "#endif\n"
    "#define _Readable_elements_(s)\n"
    "#ifdef _Readable_bytes_\n"
    "#undef _Readable_bytes_\n"
    "#endif\n"
    "#define _Readable_bytes_(s)\n"
    "#ifdef _Null_terminated_\n"
    "#undef _Null_terminated_\n"
    "#endif\n"
    "#define _Null_terminated_\n"
    "#ifdef _NullNull_terminated_\n"
    "#undef _NullNull_terminated_\n"
    "#endif\n"
    "#define _NullNull_terminated_\n"
    "#ifdef _Valid_\n"
    "#undef _Valid_\n"
    "#endif\n"
    "#define _Valid_\n"
    "#ifdef _Notvalid_\n"
    "#undef _Notvalid_\n"
    "#endif\n"
    "#define _Notvalid_\n"
    "#ifdef _Success_\n"
    "#undef _Success_\n"
    "#endif\n"
    "#define _Success_(c)\n"
    "#ifdef _Return_type_success_\n"
    "#undef _Return_type_success_\n"
    "#endif\n"
    "#define _Return_type_success_(c)\n"
    "#ifdef _On_failure_\n"
    "#undef _On_failure_\n"
    "#endif\n"
    "#define _On_failure_(a)\n"
    "#ifdef _Always_\n"
    "#undef _Always_\n"
    "#endif\n"
    "#define _Always_(a)\n"
    "#ifdef _Use_decl_annotations_\n"
    "#undef _Use_decl_annotations_\n"
    "#endif\n"
    "#define _Use_decl_annotations_\n"
    "#ifdef _Pre_defensive_\n"
    "#undef _Pre_defensive_\n"
    "#endif\n"
    "#define _Pre_defensive_\n"
    "#ifdef _Post_defensive_\n"
    "#undef _Post_defensive_\n"
    "#endif\n"
    "#define _Post_defensive_\n"
    "#ifdef _Pre_unknown_\n"
    "#undef _Pre_unknown_\n"
    "#endif\n"
    "#define _Pre_unknown_\n"
    "#ifdef _Acquires_lock_\n"
    "#undef _Acquires_lock_\n"
    "#endif\n"
    "#define _Acquires_lock_(e)\n"
    "#ifdef _Releases_lock_\n"
    "#undef _Releases_lock_\n"
    "#endif\n"
    "#define _Releases_lock_(e)\n"
    "#ifdef _Requires_lock_held_\n"
    "#undef _Requires_lock_held_\n"
    "#endif\n"
    "#define _Requires_lock_held_(e)\n"
    "#ifdef _Requires_lock_not_held_\n"
    "#undef _Requires_lock_not_held_\n"
    "#endif\n"
    "#define _Requires_lock_not_held_(e)\n"
    "#ifdef _Requires_no_locks_held_\n"
    "#undef _Requires_no_locks_held_\n"
    "#endif\n"
    "#define _Requires_no_locks_held_\n"
    "#ifdef _Guarded_by_\n"
    "#undef _Guarded_by_\n"
    "#endif\n"
    "#define _Guarded_by_(e)\n"
    "#ifdef _Write_guarded_by_\n"
    "#undef _Write_guarded_by_\n"
    "#endif\n"
    "#define _Write_guarded_by_(e)\n"
    "#ifdef _Interlocked_\n"
    "#undef _Interlocked_\n"
    "#endif\n"
    "#define _Interlocked_\n"
    "#ifdef _Post_same_lock_\n"
    "#undef _Post_same_lock_\n"
    "#endif\n"
    "#define _Post_same_lock_(e1,e2)\n"
    "#ifdef _Benign_race_begin_\n"
    "#undef _Benign_race_begin_\n"
    "#endif\n"
    "#define _Benign_race_begin_\n"
    "#ifdef _Benign_race_end_\n"
    "#undef _Benign_race_end_\n"
    "#endif\n"
    "#define _Benign_race_end_\n"
    "#ifdef _No_competing_thread_\n"
    "#undef _No_competing_thread_\n"
    "#endif\n"
    "#define _No_competing_thread_\n"
    "#ifdef _No_competing_thread_begin_\n"
    "#undef _No_competing_thread_begin_\n"
    "#endif\n"
    "#define _No_competing_thread_begin_\n"
    "#ifdef _No_competing_thread_end_\n"
    "#undef _No_competing_thread_end_\n"
    "#endif\n"
    "#define _No_competing_thread_end_\n"
    "#ifdef _Acquires_shared_lock_\n"
    "#undef _Acquires_shared_lock_\n"
    "#endif\n"
    "#define _Acquires_shared_lock_(e)\n"
    "#ifdef _Releases_shared_lock_\n"
    "#undef _Releases_shared_lock_\n"
    "#endif\n"
    "#define _Releases_shared_lock_(e)\n"
    "#ifdef _Requires_shared_lock_held_\n"
    "#undef _Requires_shared_lock_held_\n"
    "#endif\n"
    "#define _Requires_shared_lock_held_(e)\n"
    "#ifdef _Acquires_exclusive_lock_\n"
    "#undef _Acquires_exclusive_lock_\n"
    "#endif\n"
    "#define _Acquires_exclusive_lock_(e)\n"
    "#ifdef _Releases_exclusive_lock_\n"
    "#undef _Releases_exclusive_lock_\n"
    "#endif\n"
    "#define _Releases_exclusive_lock_(e)\n"
    "#ifdef _Requires_exclusive_lock_held_\n"
    "#undef _Requires_exclusive_lock_held_\n"
    "#endif\n"
    "#define _Requires_exclusive_lock_held_(e)\n"
    "#ifdef _Has_lock_kind_\n"
    "#undef _Has_lock_kind_\n"
    "#endif\n"
    "#define _Has_lock_kind_(n)\n"
    "#ifdef _Create_lock_level_\n"
    "#undef _Create_lock_level_\n"
    "#endif\n"
    "#define _Create_lock_level_(n)\n"
    "#ifdef _Has_lock_level_\n"
    "#undef _Has_lock_level_\n"
    "#endif\n"
    "#define _Has_lock_level_(n)\n"
    "#ifdef _Lock_level_order_\n"
    "#undef _Lock_level_order_\n"
    "#endif\n"
    "#define _Lock_level_order_(n1,n2)\n"
    "#ifdef _Analysis_assume_lock_acquired_\n"
    "#undef _Analysis_assume_lock_acquired_\n"
    "#endif\n"
    "#define _Analysis_assume_lock_acquired_(e)\n"
    "#ifdef _Analysis_assume_lock_released_\n"
    "#undef _Analysis_assume_lock_released_\n"
    "#endif\n"
    "#define _Analysis_assume_lock_released_(e)\n"
    "#ifdef _Analysis_assume_lock_held_\n"
    "#undef _Analysis_assume_lock_held_\n"
    "#endif\n"
    "#define _Analysis_assume_lock_held_(e)\n"
    "#ifdef _Analysis_assume_lock_not_held_\n"
    "#undef _Analysis_assume_lock_not_held_\n"
    "#endif\n"
    "#define _Analysis_assume_lock_not_held_(e)\n"
    "#ifdef _Analysis_assume_same_lock_\n"
    "#undef _Analysis_assume_same_lock_\n"
    "#endif\n"
    "#define _Analysis_assume_same_lock_(e)\n"
    "#ifdef _In_\n"
    "#undef _In_\n"
    "#endif\n"
    "#define _In_\n"
    "#ifdef _Out_\n"
    "#undef _Out_\n"
    "#endif\n"
    "#define _Out_\n"
    "#ifdef _Inout_\n"
    "#undef _Inout_\n"
    "#endif\n"
    "#define _Inout_\n"
    "#ifdef _In_z_\n"
    "#undef _In_z_\n"
    "#endif\n"
    "#define _In_z_\n"
    "#ifdef _Inout_z_\n"
    "#undef _Inout_z_\n"
    "#endif\n"
    "#define _Inout_z_\n"
    "#ifdef _In_reads_\n"
    "#undef _In_reads_\n"
    "#endif\n"
    "#define _In_reads_(s)\n"
    "#ifdef _In_reads_bytes_\n"
    "#undef _In_reads_bytes_\n"
    "#endif\n"
    "#define _In_reads_bytes_(s)\n"
    "#ifdef _In_reads_z_\n"
    "#undef _In_reads_z_\n"
    "#endif\n"
    "#define _In_reads_z_(s)\n"
    "#ifdef _In_reads_or_z_\n"
    "#undef _In_reads_or_z_\n"
    "#endif\n"
    "#define _In_reads_or_z_(s)\n"
    "#ifdef _Out_writes_\n"
    "#undef _Out_writes_\n"
    "#endif\n"
    "#define _Out_writes_(s)\n"
    "#ifdef _Out_writes_bytes_\n"
    "#undef _Out_writes_bytes_\n"
    "#endif\n"
    "#define _Out_writes_bytes_(s)\n"
    "#ifdef _Out_writes_z_\n"
    "#undef _Out_writes_z_\n"
    "#endif\n"
    "#define _Out_writes_z_(s)\n"
    "#ifdef _Inout_updates_\n"
    "#undef _Inout_updates_\n"
    "#endif\n"
    "#define _Inout_updates_(s)\n"
    "#ifdef _Inout_updates_bytes_\n"
    "#undef _Inout_updates_bytes_\n"
    "#endif\n"
    "#define _Inout_updates_bytes_(s)\n"
    "#ifdef _Inout_updates_z_\n"
    "#undef _Inout_updates_z_\n"
    "#endif\n"
    "#define _Inout_updates_z_(s)\n"
    "#ifdef _Out_writes_to_\n"
    "#undef _Out_writes_to_\n"
    "#endif\n"
    "#define _Out_writes_to_(s,c)\n"
    "#ifdef _Out_writes_bytes_to_\n"
    "#undef _Out_writes_bytes_to_\n"
    "#endif\n"
    "#define _Out_writes_bytes_to_(s,c)\n"
    "#ifdef _Out_writes_all_\n"
    "#undef _Out_writes_all_\n"
    "#endif\n"
    "#define _Out_writes_all_(s)\n"
    "#ifdef _Out_writes_bytes_all_\n"
    "#undef _Out_writes_bytes_all_\n"
    "#endif\n"
    "#define _Out_writes_bytes_all_(s)\n"
    "#ifdef _Inout_updates_to_\n"
    "#undef _Inout_updates_to_\n"
    "#endif\n"
    "#define _Inout_updates_to_(s,c)\n"
    "#ifdef _Inout_updates_bytes_to_\n"
    "#undef _Inout_updates_bytes_to_\n"
    "#endif\n"
    "#define _Inout_updates_bytes_to_(s,c)\n"
    "#ifdef _Inout_updates_all_\n"
    "#undef _Inout_updates_all_\n"
    "#endif\n"
    "#define _Inout_updates_all_(s)\n"
    "#ifdef _Inout_updates_bytes_all_\n"
    "#undef _Inout_updates_bytes_all_\n"
    "#endif\n"
    "#define _Inout_updates_bytes_all_(s)\n"
    "#ifdef _In_reads_to_ptr_\n"
    "#undef _In_reads_to_ptr_\n"
    "#endif\n"
    "#define _In_reads_to_ptr_(p)\n"
    "#ifdef _In_reads_to_ptr_z_\n"
    "#undef _In_reads_to_ptr_z_\n"
    "#endif\n"
    "#define _In_reads_to_ptr_z_(p)\n"
    "#ifdef _Out_writes_to_ptr_\n"
    "#undef _Out_writes_to_ptr_\n"
    "#endif\n"
    "#define _Out_writes_to_ptr_(p)\n"
    "#ifdef _Out_writes_to_ptr_z_\n"
    "#undef _Out_writes_to_ptr_z_\n"
    "#endif\n"
    "#define _Out_writes_to_ptr_z_(p)\n"
    "#ifdef _In_opt_\n"
    "#undef _In_opt_\n"
    "#endif\n"
    "#define _In_opt_\n"
    "#ifdef _Out_opt_\n"
    "#undef _Out_opt_\n"
    "#endif\n"
    "#define _Out_opt_\n"
    "#ifdef _Inout_opt_\n"
    "#undef _Inout_opt_\n"
    "#endif\n"
    "#define _Inout_opt_\n"
    "#ifdef _In_opt_z_\n"
    "#undef _In_opt_z_\n"
    "#endif\n"
    "#define _In_opt_z_\n"
    "#ifdef _Inout_opt_z_\n"
    "#undef _Inout_opt_z_\n"
    "#endif\n"
    "#define _Inout_opt_z_\n"
    "#ifdef _In_reads_opt_\n"
    "#undef _In_reads_opt_\n"
    "#endif\n"
    "#define _In_reads_opt_(s)\n"
    "#ifdef _In_reads_opt_z_\n"
    "#undef _In_reads_opt_z_\n"
    "#endif\n"
    "#define _In_reads_opt_z_(s)\n"
    "#ifdef _In_reads_bytes_opt_\n"
    "#undef _In_reads_bytes_opt_\n"
    "#endif\n"
    "#define _In_reads_bytes_opt_(s)\n"
    "#ifdef _Out_writes_opt_\n"
    "#undef _Out_writes_opt_\n"
    "#endif\n"
    "#define _Out_writes_opt_(s)\n"
    "#ifdef _Out_writes_bytes_opt_\n"
    "#undef _Out_writes_bytes_opt_\n"
    "#endif\n"
    "#define _Out_writes_bytes_opt_(s)\n"
    "#ifdef _Out_writes_opt_z_\n"
    "#undef _Out_writes_opt_z_\n"
    "#endif\n"
    "#define _Out_writes_opt_z_(s)\n"
    "#ifdef _Inout_updates_opt_\n"
    "#undef _Inout_updates_opt_\n"
    "#endif\n"
    "#define _Inout_updates_opt_(s)\n"
    "#ifdef _Inout_updates_bytes_opt_\n"
    "#undef _Inout_updates_bytes_opt_\n"
    "#endif\n"
    "#define _Inout_updates_bytes_opt_(s)\n"
    "#ifdef _Inout_updates_opt_z_\n"
    "#undef _Inout_updates_opt_z_\n"
    "#endif\n"
    "#define _Inout_updates_opt_z_(s)\n"
    "#ifdef _Out_writes_to_opt_\n"
    "#undef _Out_writes_to_opt_\n"
    "#endif\n"
    "#define _Out_writes_to_opt_(s,c)\n"
    "#ifdef _Out_writes_bytes_to_opt_\n"
    "#undef _Out_writes_bytes_to_opt_\n"
    "#endif\n"
    "#define _Out_writes_bytes_to_opt_(s,c)\n"
    "#ifdef _Out_writes_all_opt_\n"
    "#undef _Out_writes_all_opt_\n"
    "#endif\n"
    "#define _Out_writes_all_opt_(s)\n"
    "#ifdef _Out_writes_bytes_all_opt_\n"
    "#undef _Out_writes_bytes_all_opt_\n"
    "#endif\n"
    "#define _Out_writes_bytes_all_opt_(s)\n"
    "#ifdef _Inout_updates_to_opt_\n"
    "#undef _Inout_updates_to_opt_\n"
    "#endif\n"
    "#define _Inout_updates_to_opt_(s,c)\n"
    "#ifdef _Inout_updates_bytes_to_opt_\n"
    "#undef _Inout_updates_bytes_to_opt_\n"
    "#endif\n"
    "#define _Inout_updates_bytes_to_opt_(s,c)\n"
    "#ifdef _Inout_updates_all_opt_\n"
    "#undef _Inout_updates_all_opt_\n"
    "#endif\n"
    "#define _Inout_updates_all_opt_(s)\n"
    "#ifdef _Inout_updates_bytes_all_opt_\n"
    "#undef _Inout_updates_bytes_all_opt_\n"
    "#endif\n"
    "#define _Inout_updates_bytes_all_opt_(s)\n"
    "#ifdef _In_reads_to_ptr_opt_\n"
    "#undef _In_reads_to_ptr_opt_\n"
    "#endif\n"
    "#define _In_reads_to_ptr_opt_(p)\n"
    "#ifdef _In_reads_to_ptr_opt_z_\n"
    "#undef _In_reads_to_ptr_opt_z_\n"
    "#endif\n"
    "#define _In_reads_to_ptr_opt_z_(p)\n"
    "#ifdef _Out_writes_to_ptr_opt_\n"
    "#undef _Out_writes_to_ptr_opt_\n"
    "#endif\n"
    "#define _Out_writes_to_ptr_opt_(p)\n"
    "#ifdef _Out_writes_to_ptr_opt_z_\n"
    "#undef _Out_writes_to_ptr_opt_z_\n"
    "#endif\n"
    "#define _Out_writes_to_ptr_opt_z_(p)\n"
    "#ifdef _Outptr_\n"
    "#undef _Outptr_\n"
    "#endif\n"
    "#define _Outptr_\n"
    "#ifdef _Outptr_opt_\n"
    "#undef _Outptr_opt_\n"
    "#endif\n"
    "#define _Outptr_opt_\n"
    "#ifdef _Outptr_result_maybenull_\n"
    "#undef _Outptr_result_maybenull_\n"
    "#endif\n"
    "#define _Outptr_result_maybenull_\n"
    "#ifdef _Outptr_opt_result_maybenull_\n"
    "#undef _Outptr_opt_result_maybenull_\n"
    "#endif\n"
    "#define _Outptr_opt_result_maybenull_\n"
    "#ifdef _Outptr_result_z_\n"
    "#undef _Outptr_result_z_\n"
    "#endif\n"
    "#define _Outptr_result_z_\n"
    "#ifdef _Outptr_opt_result_z_\n"
    "#undef _Outptr_opt_result_z_\n"
    "#endif\n"
    "#define _Outptr_opt_result_z_\n"
    "#ifdef _Outptr_result_maybenull_z_\n"
    "#undef _Outptr_result_maybenull_z_\n"
    "#endif\n"
    "#define _Outptr_result_maybenull_z_\n"
    "#ifdef _Outptr_opt_result_maybenull_z_\n"
    "#undef _Outptr_opt_result_maybenull_z_\n"
    "#endif\n"
    "#define _Outptr_opt_result_maybenull_z_\n"
    "#ifdef _COM_Outptr_\n"
    "#undef _COM_Outptr_\n"
    "#endif\n"
    "#define _COM_Outptr_\n"
    "#ifdef _COM_Outptr_opt_\n"
    "#undef _COM_Outptr_opt_\n"
    "#endif\n"
    "#define _COM_Outptr_opt_\n"
    "#ifdef _COM_Outptr_result_maybenull_\n"
    "#undef _COM_Outptr_result_maybenull_\n"
    "#endif\n"
    "#define _COM_Outptr_result_maybenull_\n"
    "#ifdef _COM_Outptr_opt_result_maybenull_\n"
    "#undef _COM_Outptr_opt_result_maybenull_\n"
    "#endif\n"
    "#define _COM_Outptr_opt_result_maybenull_\n"
    "#ifdef _Outptr_result_buffer_\n"
    "#undef _Outptr_result_buffer_\n"
    "#endif\n"
    "#define _Outptr_result_buffer_(s)\n"
    "#ifdef _Outptr_result_buffer_maybenull_\n"
    "#undef _Outptr_result_buffer_maybenull_\n"
    "#endif\n"
    "#define _Outptr_result_buffer_maybenull_(s)\n"
    "#ifdef _Outptr_result_bytebuffer_\n"
    "#undef _Outptr_result_bytebuffer_\n"
    "#endif\n"
    "#define _Outptr_result_bytebuffer_(s)\n"
    "#ifdef _Outptr_result_bytebuffer_maybenull_\n"
    "#undef _Outptr_result_bytebuffer_maybenull_\n"
    "#endif\n"
    "#define _Outptr_result_bytebuffer_maybenull_(s)\n"
    "#ifdef _Outptr_opt_result_buffer_\n"
    "#undef _Outptr_opt_result_buffer_\n"
    "#endif\n"
    "#define _Outptr_opt_result_buffer_(s)\n"
    "#ifdef _Outptr_opt_result_buffer_maybenull_\n"
    "#undef _Outptr_opt_result_buffer_maybenull_\n"
    "#endif\n"
    "#define _Outptr_opt_result_buffer_maybenull_(s)\n"
    "#ifdef _Outptr_opt_result_bytebuffer_\n"
    "#undef _Outptr_opt_result_bytebuffer_\n"
    "#endif\n"
    "#define _Outptr_opt_result_bytebuffer_(s)\n"
    "#ifdef _Outptr_opt_result_bytebuffer_maybenull_\n"
    "#undef _Outptr_opt_result_bytebuffer_maybenull_\n"
    "#endif\n"
    "#define _Outptr_opt_result_bytebuffer_maybenull_(s)\n"
    "#ifdef _Outptr_result_buffer_to_\n"
    "#undef _Outptr_result_buffer_to_\n"
    "#endif\n"
    "#define _Outptr_result_buffer_to_(s,c)\n"
    "#ifdef _Outptr_result_bytebuffer_to_\n"
    "#undef _Outptr_result_bytebuffer_to_\n"
    "#endif\n"
    "#define _Outptr_result_bytebuffer_to_(s,c)\n"
    "#ifdef _Outptr_opt_result_buffer_to_\n"
    "#undef _Outptr_opt_result_buffer_to_\n"
    "#endif\n"
    "#define _Outptr_opt_result_buffer_to_(s,c)\n"
    "#ifdef _Outptr_opt_result_bytebuffer_to_\n"
    "#undef _Outptr_opt_result_bytebuffer_to_\n"
    "#endif\n"
    "#define _Outptr_opt_result_bytebuffer_to_(s,c)\n"
    "#ifdef _Ret_\n"
    "#undef _Ret_\n"
    "#endif\n"
    "#define _Ret_\n"
    "#ifdef _Ret_valid_\n"
    "#undef _Ret_valid_\n"
    "#endif\n"
    "#define _Ret_valid_\n"
    "#ifdef _Ret_z_\n"
    "#undef _Ret_z_\n"
    "#endif\n"
    "#define _Ret_z_\n"
    "#ifdef _Ret_writes_\n"
    "#undef _Ret_writes_\n"
    "#endif\n"
    "#define _Ret_writes_(s)\n"
    "#ifdef _Ret_writes_bytes_\n"
    "#undef _Ret_writes_bytes_\n"
    "#endif\n"
    "#define _Ret_writes_bytes_(s)\n"
    "#ifdef _Ret_writes_z_\n"
    "#undef _Ret_writes_z_\n"
    "#endif\n"
    "#define _Ret_writes_z_(s)\n"
    "#ifdef _Ret_writes_to_\n"
    "#undef _Ret_writes_to_\n"
    "#endif\n"
    "#define _Ret_writes_to_(s,c)\n"
    "#ifdef _Ret_writes_bytes_to_\n"
    "#undef _Ret_writes_bytes_to_\n"
    "#endif\n"
    "#define _Ret_writes_bytes_to_(s,c)\n"
    "#ifdef _Ret_writes_to_ptr_\n"
    "#undef _Ret_writes_to_ptr_\n"
    "#endif\n"
    "#define _Ret_writes_to_ptr_(p)\n"
    "#ifdef _Ret_writes_to_ptr_z_\n"
    "#undef _Ret_writes_to_ptr_z_\n"
    "#endif\n"
    "#define _Ret_writes_to_ptr_z_(p)\n"
    "#ifdef _Ret_writes_maybenull_\n"
    "#undef _Ret_writes_maybenull_\n"
    "#endif\n"
    "#define _Ret_writes_maybenull_(s)\n"
    "#ifdef _Ret_writes_bytes_maybenull_\n"
    "#undef _Ret_writes_bytes_maybenull_\n"
    "#endif\n"
    "#define _Ret_writes_bytes_maybenull_(s)\n"
    "#ifdef _Ret_writes_to_maybenull_\n"
    "#undef _Ret_writes_to_maybenull_\n"
    "#endif\n"
    "#define _Ret_writes_to_maybenull_(s,c)\n"
    "#ifdef _Ret_writes_bytes_to_maybenull_\n"
    "#undef _Ret_writes_bytes_to_maybenull_\n"
    "#endif\n"
    "#define _Ret_writes_bytes_to_maybenull_(s,c)\n"
    "#ifdef _Ret_writes_maybenull_z_\n"
    "#undef _Ret_writes_maybenull_z_\n"
    "#endif\n"
    "#define _Ret_writes_maybenull_z_(s)\n"
    "#ifdef _Ret_null_\n"
    "#undef _Ret_null_\n"
    "#endif\n"
    "#define _Ret_null_\n"
    "#ifdef _Ret_notnull_\n"
    "#undef _Ret_notnull_\n"
    "#endif\n"
    "#define _Ret_notnull_\n"
    "#ifdef _Ret_maybenull_\n"
    "#undef _Ret_maybenull_\n"
    "#endif\n"
    "#define _Ret_maybenull_\n"
    "#ifdef _Ret_maybenull_z_\n"
    "#undef _Ret_maybenull_z_\n"
    "#endif\n"
    "#define _Ret_maybenull_z_\n"
    "#ifdef _Field_size_\n"
    "#undef _Field_size_\n"
    "#endif\n"
    "#define _Field_size_(s)\n"
    "#ifdef _Field_size_opt_\n"
    "#undef _Field_size_opt_\n"
    "#endif\n"
    "#define _Field_size_opt_(s)\n"
    "#ifdef _Field_size_bytes_\n"
    "#undef _Field_size_bytes_\n"
    "#endif\n"
    "#define _Field_size_bytes_(s)\n"
    "#ifdef _Field_size_bytes_opt_\n"
    "#undef _Field_size_bytes_opt_\n"
    "#endif\n"
    "#define _Field_size_bytes_opt_(s)\n"
    "#ifdef _Field_size_part_\n"
    "#undef _Field_size_part_\n"
    "#endif\n"
    "#define _Field_size_part_(s,c)\n"
    "#ifdef _Field_size_part_opt_\n"
    "#undef _Field_size_part_opt_\n"
    "#endif\n"
    "#define _Field_size_part_opt_(s,c)\n"
    "#ifdef _Field_size_bytes_part_\n"
    "#undef _Field_size_bytes_part_\n"
    "#endif\n"
    "#define _Field_size_bytes_part_(s,c)\n"
    "#ifdef _Field_size_bytes_part_opt_\n"
    "#undef _Field_size_bytes_part_opt_\n"
    "#endif\n"
    "#define _Field_size_bytes_part_opt_(s,c)\n"
    "#ifdef _Field_size_full_\n"
    "#undef _Field_size_full_\n"
    "#endif\n"
    "#define _Field_size_full_(s)\n"
    "#ifdef _Field_size_full_opt_\n"
    "#undef _Field_size_full_opt_\n"
    "#endif\n"
    "#define _Field_size_full_opt_(s)\n"
    "#ifdef _Field_size_bytes_full_\n"
    "#undef _Field_size_bytes_full_\n"
    "#endif\n"
    "#define _Field_size_bytes_full_(s)\n"
    "#ifdef _Field_size_bytes_full_opt_\n"
    "#undef _Field_size_bytes_full_opt_\n"
    "#endif\n"
    "#define _Field_size_bytes_full_opt_(s)\n"
    "#ifdef _Printf_format_string_\n"
    "#undef _Printf_format_string_\n"
    "#endif\n"
    "#define _Printf_format_string_\n"
    "#ifdef _Scanf_format_string_\n"
    "#undef _Scanf_format_string_\n"
    "#endif\n"
    "#define _Scanf_format_string_\n"
    "#ifdef _Scanf_s_format_string_\n"
    "#undef _Scanf_s_format_string_\n"
    "#endif\n"
    "#define _Scanf_s_format_string_\n"
    "#ifdef _Printf_format_string_params_\n"
    "#undef _Printf_format_string_params_\n"
    "#endif\n"
    "#define _Printf_format_string_params_(x)\n"
    "#ifdef _Scanf_format_string_params_\n"
    "#undef _Scanf_format_string_params_\n"
    "#endif\n"
    "#define _Scanf_format_string_params_(x)\n"
    "#ifdef _Scanf_s_format_string_params_\n"
    "#undef _Scanf_s_format_string_params_\n"
    "#endif\n"
    "#define _Scanf_s_format_string_params_(x)\n"
    "#ifdef _In_range_\n"
    "#undef _In_range_\n"
    "#endif\n"
    "#define _In_range_(l,h)\n"
    "#ifdef _Out_range_\n"
    "#undef _Out_range_\n"
    "#endif\n"
    "#define _Out_range_(l,h)\n"
    "#ifdef _Ret_range_\n"
    "#undef _Ret_range_\n"
    "#endif\n"
    "#define _Ret_range_(l,h)\n"
    "#ifdef _Deref_in_range_\n"
    "#undef _Deref_in_range_\n"
    "#endif\n"
    "#define _Deref_in_range_(l,h)\n"
    "#ifdef _Deref_out_range_\n"
    "#undef _Deref_out_range_\n"
    "#endif\n"
    "#define _Deref_out_range_(l,h)\n"
    "#ifdef _Deref_inout_range_\n"
    "#undef _Deref_inout_range_\n"
    "#endif\n"
    "#define _Deref_inout_range_(l,h)\n"
    "#ifdef _Field_range_\n"
    "#undef _Field_range_\n"
    "#endif\n"
    "#define _Field_range_(l,h)\n"
    "#ifdef _Pre_equal_to_\n"
    "#undef _Pre_equal_to_\n"
    "#endif\n"
    "#define _Pre_equal_to_(e)\n"
    "#ifdef _Post_equal_to_\n"
    "#undef _Post_equal_to_\n"
    "#endif\n"
    "#define _Post_equal_to_(e)\n"
    "#ifdef _Struct_size_bytes_\n"
    "#undef _Struct_size_bytes_\n"
    "#endif\n"
    "#define _Struct_size_bytes_(s)\n"
    "#ifdef _Analysis_assume_\n"
    "#undef _Analysis_assume_\n"
    "#endif\n"
    "#define _Analysis_assume_\n"
    "#ifdef _Analysis_assume_nullterminated_\n"
    "#undef _Analysis_assume_nullterminated_\n"
    "#endif\n"
    "#define _Analysis_assume_nullterminated_(s)\n"
    "#ifdef _Analysis_mode_\n"
    "#undef _Analysis_mode_\n"
    "#endif\n"
    "#define _Analysis_mode_(m)\n"
    "#ifdef _Analysis_noreturn_\n"
    "#undef _Analysis_noreturn_\n"
    "#endif\n"
    "#define _Analysis_noreturn_\n"
    "#ifdef _Raises_SEH_exception_\n"
    "#undef _Raises_SEH_exception_\n"
    "#endif\n"
    "#define _Raises_SEH_exception_\n"
    "#ifdef _Maybe_raises_SEH_exception_\n"
    "#undef _Maybe_raises_SEH_exception_\n"
    "#endif\n"
    "#define _Maybe_raises_SEH_exception_\n"
    "#ifdef _Function_class_\n"
    "#undef _Function_class_\n"
    "#endif\n"
    "#define _Function_class_(n)\n"
    "#ifdef _Literal_\n"
    "#undef _Literal_\n"
    "#endif\n"
    "#define _Literal_\n"
    "#ifdef _Notliteral_\n"
    "#undef _Notliteral_\n"
    "#endif\n"
    "#define _Notliteral_\n"
    "#ifdef _Enum_is_bitflag_\n"
    "#undef _Enum_is_bitflag_\n"
    "#endif\n"
    "#define _Enum_is_bitflag_\n"
    "#ifdef _Strict_type_match_\n"
    "#undef _Strict_type_match_\n"
    "#endif\n"
    "#define _Strict_type_match_\n"
    "#ifdef _Points_to_data_\n"
    "#undef _Points_to_data_\n"
    "#endif\n"
    "#define _Points_to_data_\n"
    "#ifdef _Interlocked_operand_\n"
    "#undef _Interlocked_operand_\n"
    "#endif\n"
    "#define _Interlocked_operand_\n"
    "#ifdef _IRQL_raises_\n"
    "#undef _IRQL_raises_\n"
    "#endif\n"
    "#define _IRQL_raises_(i)\n"
    "#ifdef _IRQL_requires_\n"
    "#undef _IRQL_requires_\n"
    "#endif\n"
    "#define _IRQL_requires_(i)\n"
    "#ifdef _IRQL_requires_max_\n"
    "#undef _IRQL_requires_max_\n"
    "#endif\n"
    "#define _IRQL_requires_max_(i)\n"
    "#ifdef _IRQL_requires_min_\n"
    "#undef _IRQL_requires_min_\n"
    "#endif\n"
    "#define _IRQL_requires_min_(i)\n"
    "#ifdef _IRQL_saves_\n"
    "#undef _IRQL_saves_\n"
    "#endif\n"
    "#define _IRQL_saves_\n"
    "#ifdef _IRQL_saves_global_\n"
    "#undef _IRQL_saves_global_\n"
    "#endif\n"
    "#define _IRQL_saves_global_(k,s)\n"
    "#ifdef _IRQL_restores_\n"
    "#undef _IRQL_restores_\n"
    "#endif\n"
    "#define _IRQL_restores_\n"
    "#ifdef _IRQL_restores_global_\n"
    "#undef _IRQL_restores_global_\n"
    "#endif\n"
    "#define _IRQL_restores_global_(k,s)\n"
    "#ifdef _IRQL_always_function_min_\n"
    "#undef _IRQL_always_function_min_\n"
    "#endif\n"
    "#define _IRQL_always_function_min_(i)\n"
    "#ifdef _IRQL_always_function_max_\n"
    "#undef _IRQL_always_function_max_\n"
    "#endif\n"
    "#define _IRQL_always_function_max_(i)\n"
    "#ifdef _IRQL_requires_same_\n"
    "#undef _IRQL_requires_same_\n"
    "#endif\n"
    "#define _IRQL_requires_same_\n"
    "#ifdef _IRQL_uses_cancel_\n"
    "#undef _IRQL_uses_cancel_\n"
    "#endif\n"
    "#define _IRQL_uses_cancel_\n"
    "#ifdef _IRQL_is_cancel_\n"
    "#undef _IRQL_is_cancel_\n"
    "#endif\n"
    "#define _IRQL_is_cancel_\n"
    "#ifdef _Kernel_float_saved_\n"
    "#undef _Kernel_float_saved_\n"
    "#endif\n"
    "#define _Kernel_float_saved_\n"
    "#ifdef _Kernel_float_restored_\n"
    "#undef _Kernel_float_restored_\n"
    "#endif\n"
    "#define _Kernel_float_restored_\n"
    "#ifdef _Kernel_float_used_\n"
    "#undef _Kernel_float_used_\n"
    "#endif\n"
    "#define _Kernel_float_used_\n"
    "#ifdef _Kernel_acquires_resource_\n"
    "#undef _Kernel_acquires_resource_\n"
    "#endif\n"
    "#define _Kernel_acquires_resource_(k)\n"
    "#ifdef _Kernel_releases_resource_\n"
    "#undef _Kernel_releases_resource_\n"
    "#endif\n"
    "#define _Kernel_releases_resource_(k)\n"
    "#ifdef _Kernel_requires_resource_held_\n"
    "#undef _Kernel_requires_resource_held_\n"
    "#endif\n"
    "#define _Kernel_requires_resource_held_(k)\n"
    "#ifdef _Kernel_requires_resource_not_held_\n"
    "#undef _Kernel_requires_resource_not_held_\n"
    "#endif\n"
    "#define _Kernel_requires_resource_not_held_(k)\n"
    "#ifdef _Kernel_clear_do_init_\n"
    "#undef _Kernel_clear_do_init_\n"
    "#endif\n"
    "#define _Kernel_clear_do_init_(yn)\n"
    "#ifdef _Kernel_IoGetDmaAdapter_\n"
    "#undef _Kernel_IoGetDmaAdapter_\n"
    "#endif\n"
    "#define _Kernel_IoGetDmaAdapter_\n"
    "#ifdef _Outref_\n"
    "#undef _Outref_\n"
    "#endif\n"
    "#define _Outref_\n"
    "#ifdef _Outref_result_maybenull_\n"
    "#undef _Outref_result_maybenull_\n"
    "#endif\n"
    "#define _Outref_result_maybenull_\n"
    "#ifdef _Outref_result_buffer_\n"
    "#undef _Outref_result_buffer_\n"
    "#endif\n"
    "#define _Outref_result_buffer_(s)\n"
    "#ifdef _Outref_result_bytebuffer_\n"
    "#undef _Outref_result_bytebuffer_\n"
    "#endif\n"
    "#define _Outref_result_bytebuffer_(s)\n"
    "#ifdef _Outref_result_buffer_to_\n"
    "#undef _Outref_result_buffer_to_\n"
    "#endif\n"
    "#define _Outref_result_buffer_to_(s,c)\n"
    "#ifdef _Outref_result_bytebuffer_to_\n"
    "#undef _Outref_result_bytebuffer_to_\n"
    "#endif\n"
    "#define _Outref_result_bytebuffer_to_(s,c)\n"
    "#ifdef _Outref_result_buffer_all_\n"
    "#undef _Outref_result_buffer_all_\n"
    "#endif\n"
    "#define _Outref_result_buffer_all_(s)\n"
    "#ifdef _Outref_result_bytebuffer_all_\n"
    "#undef _Outref_result_bytebuffer_all_\n"
    "#endif\n"
    "#define _Outref_result_bytebuffer_all_(s)\n"
    "#ifdef _Outref_result_buffer_maybenull_\n"
    "#undef _Outref_result_buffer_maybenull_\n"
    "#endif\n"
    "#define _Outref_result_buffer_maybenull_(s)\n"
    "#ifdef _Outref_result_bytebuffer_maybenull_\n"
    "#undef _Outref_result_bytebuffer_maybenull_\n"
    "#endif\n"
    "#define _Outref_result_bytebuffer_maybenull_(s)\n"
    "#ifdef _Outref_result_buffer_to_maybenull_\n"
    "#undef _Outref_result_buffer_to_maybenull_\n"
    "#endif\n"
    "#define _Outref_result_buffer_to_maybenull_(s,c)\n"
    "#ifdef _Outref_result_bytebuffer_to_maybenull_\n"
    "#undef _Outref_result_bytebuffer_to_maybenull_\n"
    "#endif\n"
    "#define _Outref_result_bytebuffer_to_maybenull_(s,c)\n"
    "#ifdef _Outref_result_buffer_all_maybenull_\n"
    "#undef _Outref_result_buffer_all_maybenull_\n"
    "#endif\n"
    "#define _Outref_result_buffer_all_maybenull_(s)\n"
    "#ifdef _Outref_result_bytebuffer_all_maybenull_\n"
    "#undef _Outref_result_bytebuffer_all_maybenull_\n"
    "#endif\n"
    "#define _Outref_result_bytebuffer_all_maybenull_(s)\n"
    "#ifdef _In_defensive_\n"
    "#undef _In_defensive_\n"
    "#endif\n"
    "#define _In_defensive_(a)\n"
    "#ifdef _Out_defensive_\n"
    "#undef _Out_defensive_\n"
    "#endif\n"
    "#define _Out_defensive_(a)\n"
    "#ifdef _Inout_defensive_\n"
    "#undef _Inout_defensive_\n"
    "#endif\n"
    "#define _Inout_defensive_(a)\n"
    "#ifdef _Outptr_result_nullonfailure_\n"
    "#undef _Outptr_result_nullonfailure_\n"
    "#endif\n"
    "#define _Outptr_result_nullonfailure_\n"
    "#ifdef _Outptr_opt_result_nullonfailure_\n"
    "#undef _Outptr_opt_result_nullonfailure_\n"
    "#endif\n"
    "#define _Outptr_opt_result_nullonfailure_\n"
    "#ifdef _Outref_result_nullonfailure_\n"
    "#undef _Outref_result_nullonfailure_\n"
    "#endif\n"
    "#define _Outref_result_nullonfailure_\n"
    "#ifdef _Result_nullonfailure_\n"
    "#undef _Result_nullonfailure_\n"
    "#endif\n"
    "#define _Result_nullonfailure_\n"
    "#ifdef _Result_zeroonfailure_\n"
    "#undef _Result_zeroonfailure_\n"
    "#endif\n"
    "#define _Result_zeroonfailure_\n"
    "#ifdef _Acquires_nonreentrant_lock_\n"
    "#undef _Acquires_nonreentrant_lock_\n"
    "#endif\n"
    "#define _Acquires_nonreentrant_lock_(e)\n"
    "#ifdef _Releases_nonreentrant_lock_\n"
    "#undef _Releases_nonreentrant_lock_\n"
    "#endif\n"
    "#define _Releases_nonreentrant_lock_(e)\n"
    "#ifdef _Function_ignore_lock_checking_\n"
    "#undef _Function_ignore_lock_checking_\n"
    "#endif\n"
    "#define _Function_ignore_lock_checking_(e)\n"
    "#ifdef _Analysis_suppress_lock_checking_\n"
    "#undef _Analysis_suppress_lock_checking_\n"
    "#endif\n"
    "#define _Analysis_suppress_lock_checking_(e)\n"
    "#undef _Reserved_\n"
    "#define _Reserved_           _Pre_equal_to_(0) _Pre_ _Null_\n"
    "#undef _Pre_z_\n"
    "#define _Pre_z_              _Pre_ _Null_terminated_\n"
    "#undef _Post_z_\n"
    "#define _Post_z_             _Post_ _Null_terminated_\n"
    "#undef _Prepost_z_\n"
    "#define _Prepost_z_          _Pre_z_ _Post_z_\n"
    "#undef _Pre_null_\n"
    "#define _Pre_null_           _Pre_ _Null_\n"
    "#undef _Pre_maybenull_\n"
    "#define _Pre_maybenull_      _Pre_ _Maybenull_\n"
    "#undef _Pre_notnull_\n"
    "#define _Pre_notnull_        _Pre_ _Notnull_\n"
    "#undef _Pre_valid_\n"
    "#define _Pre_valid_          _Pre_notnull_ _Pre_ _Valid_\n"
    "#undef _Pre_opt_valid_\n"
    "#define _Pre_opt_valid_      _Pre_maybenull_ _Pre_ _Valid_\n"
    "#undef _Post_valid_\n"
    "#define _Post_valid_         _Post_ _Valid_\n"
    "#undef _Post_invalid_\n"
    "#define _Post_invalid_       _Post_ _Deref_ _Notvalid_\n"
    "#undef _Post_ptr_invalid_\n"
    "#define _Post_ptr_invalid_   _Post_ _Notvalid_\n"
    "#undef _Pre_readable_size_\n"
    "#define _Pre_readable_size_(s)      _Pre_ _Readable_elements_(s) _Pre_ _Valid_\n"
    "#undef _Pre_writable_size_\n"
    "#define _Pre_writable_size_(s)      _Pre_ _Writable_elements_(s)\n"
    "#undef _Pre_readable_byte_size_\n"
    "#define _Pre_readable_byte_size_(s) _Pre_ _Readable_bytes_(s) _Pre_ _Valid_\n"
    "#undef _Pre_writable_byte_size_\n"
    "#define _Pre_writable_byte_size_(s) _Pre_ _Writable_bytes_(s)\n"
    "#undef _Post_readable_size_\n"
    "#define _Post_readable_size_(s)     _Post_ _Readable_elements_(s) _Post_ _Valid_\n"
    "#undef _Post_writable_size_\n"
    "#define _Post_writable_size_(s)     _Post_ _Writable_elements_(s)\n"
    "#undef _Post_readable_byte_size_\n"
    "#define _Post_readable_byte_size_(s) _Post_ _Readable_bytes_(s) _Post_ _Valid_\n"
    "#undef _Post_writable_byte_size_\n"
    "#define _Post_writable_byte_size_(s) _Post_ _Writable_bytes_(s)\n"
    "\n"
    "#endif /* _NO_SAL_2_H_ */\n"
;

const STRING no_sal2CHeaderRawCString = {
    sizeof(no_sal2CHeaderRawCStr) - sizeof(CHAR),
    sizeof(no_sal2CHeaderRawCStr),
#ifdef _WIN64
    0,
#endif
    (PCHAR)&no_sal2CHeaderRawCStr,
};

#ifndef RawCString
#define RawCString (&no_sal2CHeaderRawCString)
#endif
