#!/usr/bin/env python3
import argparse
from pathlib import Path


def write_header(path: Path, symbol: str) -> None:
    header = (
        "// Auto-generated by generate_message_table.py. Do not edit.\n"
        "#pragma once\n"
        "#include <stddef.h>\n\n"
        f"extern const unsigned char {symbol}[];\n"
        f"extern const size_t {symbol}Size;\n"
    )
    path.write_text(header, encoding="ascii")


def write_source(path: Path, header_name: str, symbol: str, data: bytes) -> None:
    lines = []
    lines.append("// Auto-generated by generate_message_table.py. Do not edit.\n")
    lines.append("#include <stddef.h>\n")
    lines.append(f"#include \"{header_name}\"\n\n")
    lines.append(f"const unsigned char {symbol}[] = {{\n")

    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        line = "    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n"
        lines.append(line)

    lines.append("};\n")
    lines.append(f"const size_t {symbol}Size = {len(data)}u;\n")

    path.write_text("".join(lines), encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate C source/header from a message table .bin file."
    )
    parser.add_argument("--input", required=True, help="Path to .bin file")
    parser.add_argument("--output-c", required=True, help="Output .c file")
    parser.add_argument("--output-h", required=True, help="Output .h file")
    parser.add_argument(
        "--symbol",
        default="PerfectHashErrorsEnglishBin",
        help="Symbol name for the data array",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    output_c = Path(args.output_c)
    output_h = Path(args.output_h)

    data = input_path.read_bytes()

    output_c.parent.mkdir(parents=True, exist_ok=True)
    output_h.parent.mkdir(parents=True, exist_ok=True)

    write_header(output_h, args.symbol)
    write_source(output_c, output_h.name, args.symbol, data)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())