#!/usr/bin/env bash
set -euo pipefail

script_dir="$(
  cd "$(dirname "${BASH_SOURCE[0]}")"
  pwd
)"
root_dir="$(
  cd "${script_dir}/.."
  pwd
)"

usage() {
  cat <<'USAGE'
Usage: ci/generate-release-notes.sh [options]

Options:
  --tag <vX.Y.Z>        Release tag to use as HEAD of the notes range.
  --version <X.Y.Z>     Release version (converted to tag form vX.Y.Z).
  --output <path>       Output markdown file (default: ./release-notes.generated.md).
  -h, --help            Show this help.
USAGE
}

release_tag=""
release_version=""
output_path="${root_dir}/release-notes.generated.md"

while [ $# -gt 0 ]; do
  case "$1" in
    --tag)
      release_tag="$2"
      shift 2
      ;;
    --version)
      release_version="$2"
      shift 2
      ;;
    --output)
      output_path="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'error: unknown argument: %s\n' "$1" >&2
      exit 1
      ;;
  esac
done

if [ -z "$release_tag" ] && [ -n "$release_version" ]; then
  release_tag="v${release_version#v}"
fi

if [ -z "$release_tag" ] && [ -n "${GITHUB_REF_NAME:-}" ]; then
  case "${GITHUB_REF_NAME}" in
    v*)
      release_tag="${GITHUB_REF_NAME}"
      ;;
  esac
fi

if [ -z "$release_tag" ] && command -v git >/dev/null 2>&1; then
  release_tag="$(
    git -C "$root_dir" describe --tags --exact-match --match 'v[0-9]*' \
      2>/dev/null || true
  )"
fi

if [ -z "$release_tag" ]; then
  release_tag="v$(
    git -C "$root_dir" describe --tags --abbrev=0 --match 'v[0-9]*' \
      2>/dev/null || echo 0.0.0
  )"
  release_tag="${release_tag#vv}"
fi

if ! command -v git >/dev/null 2>&1; then
  printf 'error: git is required\n' >&2
  exit 1
fi

mapfile -t tags < <(git -C "$root_dir" tag --list 'v[0-9]*' --sort=version:refname)

release_tag_exists=0
previous_tag=""
for i in "${!tags[@]}"; do
  if [ "${tags[$i]}" = "$release_tag" ]; then
    release_tag_exists=1
    if [ "$i" -gt 0 ]; then
      previous_tag="${tags[$((i - 1))]}"
    fi
    break
  fi
done

if [ "$release_tag_exists" -eq 0 ] && [ "${#tags[@]}" -gt 0 ]; then
  previous_tag="${tags[$(( ${#tags[@]} - 1 ))]}"
fi

range=""
if [ -n "$previous_tag" ]; then
  if [ "$release_tag_exists" -eq 1 ]; then
    range="${previous_tag}..${release_tag}"
  else
    range="${previous_tag}..HEAD"
  fi
elif [ "$release_tag_exists" -eq 1 ]; then
  range="$release_tag"
else
  range="HEAD"
fi

extract_section() {
  local heading="$1"
  local file="$2"
  awk -v heading="$heading" '
    $0 == heading { in_section = 1; next }
    in_section && /^## / { exit }
    in_section { print }
  ' "$file"
}

curated_notes=""
notes_file="${root_dir}/RELEASE-NOTES.md"
if [ -f "$notes_file" ]; then
  curated_notes="$(extract_section "## ${release_tag}" "$notes_file")"
  if [ -z "$curated_notes" ]; then
    curated_notes="$(extract_section "## Unreleased" "$notes_file")"
  fi
fi

commit_lines="$(git -C "$root_dir" log --no-merges --pretty='- %h %s (%an)' $range 2>/dev/null || true)"

mkdir -p "$(dirname "$output_path")"

{
  printf '# PerfectHash %s\n\n' "$release_tag"
  printf '_Generated by `ci/generate-release-notes.sh`._\n\n'

  if [ -n "$curated_notes" ]; then
    printf '## Curated Notes\n\n'
    printf '%s\n\n' "$curated_notes"
  fi

  printf '## Commit Summary\n\n'
  if [ -n "$previous_tag" ]; then
    printf -- '- Range: `%s`\n' "$range"
  else
    printf -- '- Range: `%s` (no prior release tag found)\n' "$range"
  fi
  printf '\n'

  if [ -n "$commit_lines" ]; then
    printf '%s\n' "$commit_lines"
  else
    printf -- '- No commits found in range.\n'
  fi
} > "$output_path"

printf 'Wrote release notes: %s\n' "$output_path"
